import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { services } from "../../content";

export function generateStaticParams() {
  return services.map(({ slug }) => ({ slug }));
}

export default async function ServiceDetail({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const service = services.find((item) => item.slug === slug);
  if (!service) notFound();
  const isLakeland = slug === "single-page-website";
  const isMultiverse = slug === "five-page-website";
  const processBlock = <div className="process-block"><p className="kicker">{isMultiverse ? "How we work" : "How we do it"}</p><ol>{service.process.map((item, index) => <li key={item}><b>0{index + 1}</b><span>{item}</span></li>)}</ol></div>;

  return <main data-service={slug} className={`article-page${isLakeland ? " single-page-service" : ""}${isMultiverse ? " multiverse-service" : ""}${slug === "website-support" ? " website-support-service" : ""}`}>
    <header className="article-hero shell">
      <div><Link className="back-link" href="/services">← All services</Link><p className="kicker">Service guide · {service.price}</p><h1 className={slug === "website-transfer" ? "website-transfer-title" : slug === "strategy-session" ? "strategy-session-title" : slug === "business-consulting" ? "business-consulting-title" : slug === "brand-advertising-plan" ? "brand-advertising-title" : undefined}>{slug === "website-transfer" ? <><span>Domain Change &amp;</span>{" "}<span>Website Transfer</span></> : service.name}</h1><p className="intro">{service.intro}</p></div>
      <div className="article-image"><Image src={service.image} alt={isLakeland ? "Lakeland Cabaret website homepage" : isMultiverse ? "The Multiverse Adventurers Guild home page" : "Whimsy campaign work"} fill priority sizes="(max-width: 700px) 100vw, 45vw"/></div>
    </header>
    <section className="article-body shell">{isMultiverse && processBlock}<article><p className="kicker">What we do</p><h2 className="useful-work-title">{isMultiverse ? <><span>Design around your needs,</span>{" "}<span>then exceed your expectations.</span></> : <><span>Useful work, shaped</span>{" "}<span>around your real goal.</span></>}</h2>{isMultiverse ? <ul><li><p>We’ll start with a free consultation. We’ll gather your needs and desire with a focus on creating an actionable plan. You’ll leave the meeting with a list of details to gather and a contract laying out the work to be done. This will cover a 50% down payment, pages to be created, timeframe for completion, and a firm definition of done.</p></li><li><p>From there we’ll get to work. We’ll transfer or purchase your domain, build your website, and get you access to manage it. We can train your staff to handle ongoing changes or work to set up a long-term support plan. When we’re done we’ll publish publicly and hand things off to your company.</p><p>After completion we offer content update services, advertising plans, and business strategies to keep you ahead of the curve. Questions about the details? Don’t hesitate to ask!</p></li></ul> : <><p>We bring strategy, clear communication, and hands-on execution together. The scope stays understandable, the recommendations stay practical, and every choice connects back to the people you need to reach.</p><p>Whimsy works especially well with local businesses and community organizations that want an experienced partner without adding a large agency process.</p></>}</article><aside className="article-callout"><p className="kicker">What we need</p><ul>{service.need.map((item) => <li key={item}>{item}</li>)}</ul></aside>{!isMultiverse && processBlock}{isLakeland && <section className="featured-site">
      <div><p className="kicker">Featured single-page website</p><h2>Lakeland Cabaret</h2><p>Lakeland Cabaret needed one lively, easy-to-navigate destination for a wonderfully varied offering: music and DJ services, fire performance, photography and video, wedding ceremonies, pricing, and contact details.</p><p>The finished page gives each service room to shine while carrying visitors through one continuous story—from the opening promise to clear pricing and a direct invitation to plan an event.</p><a className="button outline" href="https://lakelandcabaret.com/" target="_blank" rel="noopener noreferrer">Visit the live website ↗</a></div>
      <ul><li><b>One page, many services</b><span>A clear structure keeps a broad creative offering understandable.</span></li><li><b>Personality first</b><span>Bold imagery and playful copy capture the team’s sense of wonder.</span></li><li><b>Built to convert</b><span>Service details, pricing, and contact paths live in one smooth journey.</span></li><li><b>Designed to grow</b><span>The site is ready to be updated, changed, and expanded as the team’s services evolve.</span></li></ul>
    </section>}{isMultiverse && <section className="mag-showcase">
      <header><p className="kicker">Featured five-page website</p><h2>Multiverse Adventurers Guild</h2><p>This project shows how a multi-page website can grow beyond publishing information. The complete rules, player guides, and Game Master material connect to a working character tool that people can use while they play.</p><a className="button" href="https://multiverseadventurersguild.com/" target="_blank" rel="noopener noreferrer">Explore the live website ↗</a></header>
      <figure className="mag-sheet"><Image src="/services/multiverse/playable-sheet-small.png" alt="Interactive Multiverse Adventurers Guild character sheet with editable stats, skills, and dice controls" width={3807} height={1869} sizes="(max-width: 700px) 100vw, 80vw"/><figcaption>A playable sheet—not a static form</figcaption></figure>
      <div className="mag-capabilities"><article><b>Interactive character sheet</b><p>Players create and edit heroes, calculate derived values, manage equipment, and roll checks, attacks, and damage directly in the page.</p></article><article><b>Private browser memory</b><p>Characters save in the browser with explicit save and autosave options, then return in a library without requiring an account or database.</p></article><article><b>Portable files</b><p>Players can export a character as a named <code>.MAGHero</code> file, then load and validate that file later or move it to another device.</p></article><article><b>Connected content</b><p>Character-sheet labels link to the exact supporting rules, turning multiple content pages and the interactive tool into one useful system.</p></article></div>
      <div className="mag-responsive"><div><p className="kicker">Built for real use</p><h3><span>Complex tools can still</span>{" "}<span>work on a phone.</span></h3><p>The layout reorganizes controls and game information for smaller screens instead of simply shrinking the desktop experience. That keeps character creation, saved heroes, rules, and play tools useful wherever the audience needs them.</p><figure><Image src="/services/multiverse/command-window.png" alt="Multiverse Adventurers Guild command window with typed and spoken commands" width={1600} height={1265} sizes="(max-width: 700px) 100vw, 28vw"/><figcaption>Typed and spoken commands add another layer of interaction</figcaption></figure></div><Image src="/services/multiverse/character-library-mobile.png" alt="Playable Multiverse Adventurers Guild character sheet on a mobile phone" width={655} height={1411} sizes="(max-width: 700px) 70vw, 24vw"/><Image src="/services/multiverse/home-page-mobile.png" alt="Multiverse Adventurers Guild homepage on a mobile phone with links to rules, player guides, and characters" width={390} height={972} sizes="(max-width: 700px) 70vw, 24vw"/></div>
    </section>}<article><p className="kicker">Deliverables</p><h2 className="momentum-title">You leave with momentum.</h2><ul className="deliverables">{service.deliverables.map((item) => <li key={item}>{item}</li>)}</ul></article></section>
    <section className="article-cta"><div className="shell"><p className="kicker">Ready when you are</p><h2>Let’s make the next step clear.</h2><Link className="button" href="/contact">Book a consultation →</Link></div></section>
  </main>;
}
