const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url'),{chromium}=require('playwright'),sharp=require('sharp');
const root=path.resolve(process.env.SMOKE_REVIEW_ROOT||'reports/smoke-review-work');
(async()=>{const m=JSON.parse(fs.readFileSync(path.join(root,'manifest.json'),'utf8'));
assert(m.completedAt);assert.equal(m.captures.length,m.routes.length*38);assert.equal(new Set(m.captures.map(c=>c.id)).size,m.captures.length);
assert(m.routes.every(r=>r==='/work'||r.startsWith('/work/')));
for(const r of m.routes)assert.equal(m.captures.filter(c=>c.route===r).length,38);
for(const c of m.captures){const meta=await sharp(path.join(root,c.file)).metadata();assert.equal(meta.width,c.width,c.id);assert.equal(meta.height,c.imageHeight,c.id);assert(Math.abs(meta.height-c.pageHeight*c.zoom/100)<=2,c.id);assert(Math.abs(c.cssWidth-c.width*100/c.zoom)<2,c.id);}
const warnings=m.captures.filter(c=>c.issues.length),browser=await chromium.launch();
try{const context=await browser.newContext({viewport:{width:1600,height:1000},acceptDownloads:true}),p=await context.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));
await p.goto(pathToFileURL(path.join(root,'index.html')).href);
assert.equal(await p.locator('#pages button').count(),m.routes.length);
assert.equal(await p.locator('#sizes button').count(),38);
assert.equal(await p.locator('#before').count(),0);
await p.locator('#group').selectOption('phone');assert.equal(await p.locator('#sizes button').count(),6);
await p.locator('#current').evaluate(i=>i.decode());
const first=await p.locator('#reference').textContent();await p.keyboard.press('Alt+ArrowRight');assert.notEqual(await p.locator('#reference').textContent(),first);
await p.locator('#current').evaluate(i=>i.decode());await p.locator('#viewer').evaluate(e=>e.scrollTop=(e.scrollHeight-e.clientHeight)*.4);
await p.locator('#next').click();await p.locator('#current').evaluate(i=>i.decode());await p.waitForTimeout(100);
const ratio=await p.locator('#viewer').evaluate(e=>e.scrollTop/(e.scrollHeight-e.clientHeight));assert(Math.abs(ratio-.4)<.03,'Keep scroll position');
await p.locator('#flag').click();await p.locator('#note').fill('Review test note');
const flaggedId=await p.evaluate(()=>document.getElementById('reference').textContent.match(/capture=([^ |]+)/)[1]);
const downloadEvent=p.waitForEvent('download');await p.locator('#export').click();const download=await downloadEvent,notes=JSON.parse(fs.readFileSync(await download.path(),'utf8'));assert.equal(notes.captures[flaggedId].note,'Review test note');assert.equal(notes.captures[flaggedId].status,'flagged');
await p.reload();assert.equal(await p.locator('#note').inputValue(),'Review test note');assert.equal(await p.locator('#decision').inputValue(),'flagged');
notes.captures[flaggedId].status='approved';await p.locator('#import').setInputFiles({name:'notes.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(notes))});await p.waitForFunction(()=>document.getElementById('notice').textContent==='Review notes imported.');assert.equal(await p.locator('#decision').inputValue(),'approved');
await p.locator('#import').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({...notes,sourceTree:'wrong'}))});await p.waitForFunction(()=>document.getElementById('notice').textContent.startsWith('Import failed:'));
await p.locator('#filter').selectOption('flagged');assert.equal(await p.locator('#sizes button').count(),0);assert(await p.locator('#next').isDisabled());
await p.locator('#filter').selectOption('');await p.locator('#group').selectOption('zoom');assert.equal(await p.locator('#sizes button').count(),8);
await p.keyboard.press('Alt+ArrowDown');assert.match(await p.locator('#reference').textContent(),new RegExp(m.routes[1]));
await p.locator('#scale').selectOption('actual');assert(await p.locator('#viewer').evaluate(e=>e.classList.contains('actual')));
await p.locator('#search').fill('Work overview');assert.equal(await p.locator('#pages button').count(),1);await p.locator('#search').fill('');
await p.locator('#group').selectOption('phone');await p.locator('#approve').click();assert.equal(await p.locator('#decision').inputValue(),'pending');
await p.evaluate(()=>localStorage.clear());await p.reload();await p.locator('#next-page').click();await p.locator('#current').evaluate(i=>i.decode());await p.screenshot({path:path.join(root,'dashboard-preview.jpg'),type:'jpeg',quality:85});
await p.setViewportSize({width:390,height:844});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Mobile dashboard overflow');assert.deepEqual(errors,[]);
fs.writeFileSync(path.join(root,'validation.json'),JSON.stringify({checkedAt:new Date().toISOString(),captures:m.captures.length,pages:m.routes.length,warnings:warnings.length,dashboard:'passed',sourceTree:m.sourceTree,checks:['Work-linked routes only','38 captures per page','full-page dimensions','actual browser zoom','size groups','keyboard navigation','scroll preservation','notes and decisions persist','export/import','reject mismatched imports','empty filters','page search','approve and next','mobile dashboard']},null,2));
console.log('Validated '+m.captures.length+' captures; '+warnings.length+' capture warnings; dashboard passed.');
if(warnings.length)console.log(JSON.stringify(warnings.map(c=>({id:c.id,issues:c.issues})),null,2));
}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
