type StorySection = { kicker: string; title: string; paragraphs: string[]; images: [string, string][]; galleryLayout?: "stacked" };
export type ArchiveStory = { title?: string; summary: string; heading: string | [string, string]; introduction: string[]; hero: [string, string]; services: string[]; sections: StorySection[]; video?: string };

export const archiveStories: Record<string, ArchiveStory> = {
  "malloween": {
    summary: "A Halloween campaign bringing costumes, trick-or-treating, music, food, and independent vendors together at Jackson Crossing.",
    heading: ["One spooky afternoon.", "Plenty of reasons to explore."],
    introduction: ["The second annual Malloween invited families to Jackson Crossing on October 26, from noon to 5 PM. Costumes and candy stops gave the day its Halloween character, while local vendors, food, photography, and entertainment offered reasons to spend time throughout the mall.", "Whimsy's campaign gave those participants individual promotions within the larger event. Each piece connected a specific attraction with the Malloween invitation, helping visitors see what they could discover before they arrived."],
    hero: ["944490211038597", "Malloween promotion for Lakeland Cabaret's spooky DJ set"],
    services: ["Campaign design", "Event advertising", "Vendor promotions"],
    sections: [
      { kicker: "Things to do", title: "Give the activities their own invitation.", paragraphs: ["The entertainment promotions introduced Lakeland Cabaret's DJ set, local dance classes, a Studio One Photography session, and a Stitch appearance. Each ad offered a different reason to stop, with event details repeated where visitors needed them.", "The photography piece used an autumn backdrop, while the DJ artwork leaned into darker Halloween imagery. Those individual styles gave each activity personality within a shared seasonal campaign."], images: [["944490197705265", "Malloween promotion for local dance classes"], ["944490221038596", "Studio One Photography's autumn photo session at Malloween"], ["944490214371930", "Malloween Stitch appearance announcement for 4 to 5 PM"]] },
      { kicker: "Food and shopping", title: "Let each business bring something different.", paragraphs: ["F'ing Fantastic Food Truck's promotion highlighted egg rolls, fries, and nachos, with the event announcement directing visitors to the truck outside Dunham's. Other pieces introduced clothing, home décor, handmade jewelry, and sweets.", "Product photographs make the variety tangible. Someone arriving for Halloween activities could also discover a local maker, browse a display, or plan a food stop as part of the same visit."], images: [["944490204371931", "Food truck advertisement for Malloween"], ["944490191038599", "BINHI clothing collection promotion for Malloween"], ["944490217705263", "Home décor and seasonal displays promoted for Malloween"], ["944490207705264", "Handmade jewelry promotion for the Halloween event"], ["944490201038598", "McCallister Creations sweets promotion in the Malloween campaign"], ["944490194371932", "Enchanted Chains permanent jewelry promotion for Malloween"]] },
      {
        kicker: "The event in action",
        title: "Music, games, and reasons to stay.",
        galleryLayout: "stacked",
        paragraphs: [
          "Visitors loved the music from Lakeland Cabaret’s DJ, gathering around the booth and enjoying the Halloween atmosphere. Attendees explored the shops and event vendors throughout Jackson Crossing, finding treats, gifts, and plenty of local businesses to discover along the way.",
          "Kids joined in musical chairs and freeze dance, with candy and prizes adding to the excitement. The games gave families a chance to play, cheer one another on, and enjoy the afternoon together, turning a shopping trip into a shared Halloween celebration.",
        ],
        images: [
          ["malloween-crowd", "Costumed shoppers exploring stores and vendor displays at Jackson Crossing during Malloween."],
          ["malloween-dj", "Visitors gathering around Lakeland Cabaret’s DJ booth during Malloween."],
          ["malloween-games", "Halloween costumes and family activities beside the Malloween DJ booth."],
        ],
      },
      {
        kicker: "The value of bringing people together",
        title: "A memorable day for visitors. New connections for businesses.",
        paragraphs: [
          "For the shops and participating vendors, Malloween brought people into the halls and gave them reasons to browse, ask questions, and spend time with local businesses. Whimsy’s advertising introduced the offerings before the event, while the music and activities created opportunities to turn that interest into conversations and customer relationships.",
          "For attendees, shopping, music, games, candy, and prizes came together in one welcoming outing. Families could make memories and discover something new, while businesses had a chance to become part of those memories. That shared value gives people a reason to return and helps local businesses build lasting connections with their community.",
        ],
        images: [],
      },
    ],
  },
  "valentines-at-jackson-crossing": {
    summary: "Valentine's promotions connecting gifts, photography, and local businesses with seasonal visits to Jackson Crossing.",
    heading: "Make the occasion personal. Make the details clear.",
    introduction: ["Valentine's Day gives local businesses a chance to offer something thoughtful: a gift, a photograph, or time spent together. Whimsy's Jackson Crossing work includes a floral gift promotion and photography-led creative connected to Cupid's Corner.", "These pieces come from separate Valentine's campaigns. Each keeps its own offer and dates, showing how the occasion can support different businesses while giving customers a clear next step."],
    hero: ["1040973861390231", "Peggy's Custom Floral Designs Valentine's promotion for February 13 and 14, 2025"],
    services: ["Seasonal advertising", "Graphic design", "Business promotion"],
    sections: [
      { kicker: "Valentine's gifts · 2025", title: "Show the gift, then explain where to find it.", paragraphs: ["Peggy's Custom Floral Designs' advertisement pairs floral borders with photographs of decorated gift arrangements. Pink, red, and heart details make the occasion immediately recognizable, while the products remain central to the invitation.", "The ad lists February 13 and 14 at Jackson Crossing, including different hours for each day. That information helps shoppers plan a visit around a short seasonal window: Thursday from 11 AM to 6 PM and Friday from 11 AM to 5 PM."], images: [] },
      { kicker: "Photography and Cupid's Corner · 2024", title: "Connect a seasonal offer to a larger gathering.", paragraphs: ["Studio One Photography's earlier creative uses a bold red portrait, hearts, and a booking prompt to introduce Valentine's specials. The supporting information connects the piece to Cupid's Corner on February 14, from 2 to 6 PM, with photography, live music, vendors, and food.", "The two campaigns show different ways to approach the same occasion. A product-led invitation helps someone choose a gift; a portrait-led promotion helps them picture an experience. In both, the seasonal design works alongside the practical details customers need to take part."], images: [["787291360091817", "Studio One Photography Valentine's specials and Cupid's Corner event promotion"]] },
    ],
  },
  "happy-harvest": {
    summary: "Autumn advertising and vendor coordination for Happy Harvest at Jackson Crossing, bringing local makers, treats, and music into one seasonal event.",
    heading: "A fall gathering built around local discoveries.",
    introduction: ["Happy Harvest brought vendors and entertainment to Jackson Crossing on November 23. Whimsy assisted with advertising and curating the vendor group, connecting the seasonal event with the businesses and makers taking part.", "The campaign combined a broad vendor announcement with individual features for music, jewelry, and sweet treats. Warm colors, leaves, and harvest details gave the event its own autumn identity."],
    hero: ["974588278028790", "Happy Harvest vendor announcement with autumn leaves"],
    services: ["Event advertising", "Vendor coordination", "Campaign design"],
    sections: [
      { kicker: "The entertainment", title: "Give visitors a reason to stay awhile.", paragraphs: ["Lakeland Cabaret's promotion placed its DJ services within the Happy Harvest event and identified the location beside Alpha Koney. The entertainment became part of the invitation to explore the halls and spend time with the participating businesses.", "That connection gives a vendor event a fuller sense of occasion. Visitors can browse at their own pace while music provides another point of interest during the day."], images: [["974588071362144", "Lakeland Cabaret DJ promotion for Happy Harvest on November 23"]] },
      { kicker: "Meet the vendors", title: "Turn a list of names into things to discover.", paragraphs: ["Individual advertisements introduced Spoons, Rings & Other Bling, Ashley Sweet Creations, JoJo's Flavorful Delights, and Enchanted Chains. Jewelry photographs and baked goods gave visitors a closer look at what each participant brought to the event.", "The full vendor announcement tied those individual stories back together. Whimsy's follow-up recognized the businesses involved and the work of assembling the group, carrying the campaign through from invitation to acknowledgment."], images: [["974588108028807", "Spoons, Rings & Other Bling promotion for Happy Harvest"], ["974588138028804", "Ashley Sweet Creations Happy Harvest advertisement"], ["974588164695468", "JoJo's Flavorful Delights baked goods advertisement"], ["974588238028794", "Enchanted Chains jewelry promotion for Happy Harvest"]] },
    ],
  },
  "santa-stories": {
    summary: "Holiday storytime, library resources, and photographs of the small moments that made families feel welcome at Jackson Crossing.",
    heading: "A little Christmas magic. A reason to read together.",
    introduction: ["Santa Stories brought Jackson District Library into the holiday setting at Jackson Crossing. Families could settle in for a story, meet Santa, and discover the library's resources during a visit to the mall.", "Whimsy joined the day as Santa's elf and photographed the experience. The story lives in the details: a book held up for the children, a quiet conversation with Santa, and a reading space framed by presents and Christmas decorations."],
    hero: ["1266008515553430", "Santa reading to a child in the Christmas storytime setting"],
    services: ["Event participation", "Photography", "Community storytelling"],
    sections: [
      { kicker: "The partnership", title: "The library became part of the celebration.", paragraphs: ["Jackson District Library's table gave families a place to learn more while Santa made reading part of the holiday experience. The photographs show both sides of the visit: the festive attraction and the community resource behind it.", "That connection gives an event story more substance. The library belongs in the coverage alongside Santa, so families can recognize the people and services that helped make the day possible."], images: [["1266008452220103", "Jackson District Library's information table"], ["1266008478886767", "The Night Before Christmas book during storytime"]] },
      { kicker: "The experience", title: "Make room for the moments between poses.", paragraphs: ["Alongside the reading, we captured greetings, the decorated setting, and Santa's visits around the mall. These are different parts of the same experience, from a child's close-up conversation to a familiar local vendor joining the fun.", "The resulting collection lets the event be remembered as a day people shared. It also gives future invitations real examples of what a welcoming holiday activity can look like."], images: [["1266008422220106", "Santa preparing for storytime"], ["1266008545553427", "A child talking with Santa"], ["1266008588886756", "The decorated storytime space and books"], ["1266008622220086", "Santa visiting a food truck outside Jackson Crossing"]] },
    ],
  },
  "black-friday-coverage": {
    summary: "A holiday photo story following Santa through Jackson Crossing, connecting seasonal excitement with the stores and people in the halls.",
    heading: "Follow the energy through the whole mall.",
    introduction: ["Whimsy photographed Black Friday and Santa Stories during a busy holiday week at Jackson Crossing. With Santa moving through the halls, the coverage had a natural thread: familiar storefronts, conversations with employees, and families enjoying the seasonal setting.", "The photographs below follow the mall visits from that shared holiday-week collection. They show the retail setting and the people within it, giving the story more range than a single picture at Santa's chair."],
    hero: ["1271099948377620", "Santa greeting visitors beside the Jackson Crossing carousel"],
    services: ["On-location photography", "Retail storytelling", "Seasonal coverage"],
    sections: [
      { kicker: "Around the halls", title: "Give the businesses a place in the story.", paragraphs: ["Santa's visits created an opportunity to photograph the people behind the stores. Clothing displays, shop counters, and seasonal merchandise make each stop recognizable while the portraits keep the mood friendly.", "A collection like this offers several ways to share one occasion. Individual businesses can be featured in their own moment, while a broader photo story shows the variety visitors can find throughout the mall."], images: [["1271100248377590", "Santa posing with employees in a clothing store"], ["1271100488377566", "Santa visiting a store employee at the counter"], ["1271100661710882", "Santa waving from a shop aisle"], ["1271100695044212", "Santa and a local shopkeeper"]] },
      { kicker: "The holiday setting", title: "Photograph the place as well as the occasion.", paragraphs: ["The carousel, decorated halls, and seasonal displays help tell visitors where the experience happened. Wide views establish the location; closer photographs bring attention back to the greetings and details people remember.", "This collection comes from the shared Black Friday and Santa Stories holiday week. Together, the images connect the seasonal setting with the shopkeepers, employees, and visitors who brought it to life."], images: [["1271099911710957", "Snow along the outdoor storefronts at Jackson Crossing"], ["1271100135044268", "The carousel and visitors in the mall"], ["1271100588377556", "Santa visiting a decorated display"], ["1271100898377525", "Santa walking through the halls with visitors"], ["1271100935044188", "Santa beside the carousel horses"]] },
    ],
  },
  "holiday-commercial": {
    summary: "A Jackson Crossing holiday commercial with Whimsy handling the script, direction, and casting, alongside filming and editing by Media Advantage.",
    heading: "A seasonal invitation, made for the screen.",
    introduction: ["Jackson Crossing's holiday commercial brought the mall's seasonal message to television. Whimsy worked with Jackson Crossing and Media Advantage, contributing the script, direction, and casting that shaped what viewers would see and hear.", "Media Advantage filmed and edited the commercial. That division of work brought creative planning and production together, carrying the invitation from a written concept through to the finished spot."],
    hero: ["holiday-commercial-poster", "A frame from the Jackson Crossing holiday commercial"],
    video: "/work/archive/holiday-commercial.mp4",
    services: ["Scriptwriting", "Creative direction", "Casting"],
    sections: [
      { kicker: "Before the cameras", title: "Give a short spot a clear purpose.", paragraphs: ["A commercial needs an understandable message within a limited running time. The script supplies that structure: what the audience needs to know, how the setting supports the invitation, and how the on-screen action moves the story forward.", "Whimsy's role connected the written message with direction and casting. Those choices work together, so the people appearing in the spot feel like part of the same holiday experience the script describes."], images: [] },
      { kicker: "The finished commercial", title: "Local creative work with a wider audience.", paragraphs: ["The archived release lists HGTV, USA, Food Network, TBS, Bravo, AMC, TLC, Entertainment, and Freeform among the channels carrying the spot. The commercial above is the finished work from that release.", "The collaboration carried the idea through distinct stages of production. Whimsy shaped the script and on-camera direction; Media Advantage brought the filming and edit. Together, those contributions gave Jackson Crossing a complete holiday advertisement."], images: [] },
    ],
  },
  "student-art-show": {
    summary: "Campaign artwork, participant promotions, and local media visibility for student creativity at Jackson Crossing across multiple annual art shows.",
    heading: "Turn the halls into a place to discover young artists.",
    introduction: ["The Jackson County Student Art Show brings local K–12 artwork into the halls of Jackson Crossing. Whimsy's work helped invite families, recognize participating schools, and promote the food and entertainment surrounding the show.", "Our archive documents several years of the event. The pieces here are grouped by edition, so each invitation keeps its own dates, participants, and purpose rather than becoming one blended event."],
    hero: ["1385435016944112", "Student Art Show invitation for April 20 through May 4, 2026"],
    services: ["Campaign design", "Event promotion", "Partner features"],
    sections: [
      { kicker: "The 2026 invitation", title: "Let the artwork lead.", paragraphs: ["The 2026 invitation places a colorful student artwork at the center, with the show dates and Jackson Crossing location arranged around it. The accompanying announcement invited visitors to an opening celebration with live entertainment, food, and hundreds of pieces to discover.", "The two versions give the main invitation and its supporting acknowledgments room to be read. The work being celebrated remains the first thing a visitor sees."], images: [["1385435050277442", "2026 Student Art Show invitation with sponsor acknowledgments"]] },
      { kicker: "The 2025 campaign", title: "Help visitors find their way into the show.", paragraphs: ["The 2025 artwork introduced the exhibition, recognized participating schools, and supplied a map of the displays. These pieces answer different questions: why to visit, who is involved, and where to go once you arrive.", "Keeping those jobs distinct lets a visually lively campaign remain useful. A family looking for a school's display needs practical directions as much as an invitation."], images: [["1088502653304018", "2025 Student Art Show poster"], ["1088502739970676", "2025 art show school and participant acknowledgments"], ["1088502793304004", "2025 student artwork location map"]] },
      { kicker: "The 2024 appreciation day", title: "Give the celebration its own supporting cast.", paragraphs: ["The earlier show included a student and teacher appreciation day, with food trucks and music alongside artwork from more than 25 local schools. Whimsy created focused promotions for Petey's Donuts, F'ing Fantastic Food Truck, and the Two Soups duo.", "The archive also records this campaign artwork appearing during JTV's art show interview. Together, the pieces show how a main event can extend into partner promotions and local media coverage."], images: [["822363509917935", "Petey's Donuts promotion for the 2024 appreciation day"], ["822363549917931", "Food truck promotion for the 2024 appreciation day"], ["822363589917927", "Two Soups live music promotion for the 2024 art show"]] },
    ],
  },
  "community-day": {
    summary: "Planning conversations and local media coordination ahead of a Jackson Crossing gathering centered on food, fun, and community resources.",
    heading: "Build the invitation before the day arrives.",
    introduction: ["Community Day at Jackson Crossing was planned for June 13, with food, activities, and local resources in the halls. Whimsy's archive follows the preparation: time spent discussing the event and a visit from Channel 6 to talk about what was happening at the mall.", "This part of event work happens before the public gathering. It connects the plans with an understandable invitation and gives local organizations a place in the conversation."],
    hero: ["1432439228910357", "Channel 6 filming inside Jackson Crossing ahead of Community Day"],
    services: ["Event planning", "Media coordination", "Community promotion"],
    sections: [
      { kicker: "The preparation", title: "Start with what the community can use.", paragraphs: ["The planning post described a day of fun, food, and community resources. Bringing those elements together gives families multiple reasons to visit and lets an event introduce useful local services in a familiar setting.", "The preparation and media visit gave that invitation a starting point. Our role connected behind-the-scenes planning with the public conversation about the upcoming day."], images: [] },
      { kicker: "Local media", title: "Connect the event with the wider story of the mall.", paragraphs: ["Sean Graney from Channel 6 visited to discuss Jackson Crossing, the new Cascades Humane Society location, and the upcoming Community Day. Those subjects gave the conversation a concrete local focus: new activity in the halls and ways the community could take part.", "Media coordination works best when there is a useful story to tell. Here, the event and the nonprofit's new location offered related reasons to pay attention to what was happening at Jackson Crossing."], images: [["1432439262243687", "Kay at Jackson Crossing during the Channel 6 visit"]] },
    ],
  },
  "fetch-market-launch": {
    summary: "Consulting and media marketing for Fetch Market & Deli, introducing Chef Gretchen's plans for a new food and market destination in downtown Brooklyn.",
    heading: "Help a new business become familiar before it opens.",
    introduction: ["Fetch Market & Deli began sharing its plans for a downtown Brooklyn corner location before the doors opened. Whimsy partnered with Fetch for consulting and media marketing, including kitchen visits and early conversations about the menu.", "The early story introduced Chef Gretchen, known locally for her work at Atlas, and the combination of fresh foods, local goods, and specialty market finds planned for the space. It gave people something specific to follow as the business took shape."],
    hero: ["1447327190754894", "Fetch Market sign and Chef Gretchen in an early business announcement"],
    services: ["Business consulting", "Launch messaging", "Media marketing"],
    sections: [
      { kicker: "Introduce the idea", title: "A familiar corner with something new on the way.", paragraphs: ["The first images establish the downtown building and the space inside it. Showing the location helps neighbors place the business in their own routines, while the menu and market description explains why they might return.", "These pre-opening photographs document the project taking shape. Sharing the building and interior gives the early story a sense of place as plans for the market develop."], images: [["1447327210754892", "The downtown Brooklyn building planned for Fetch Market"], ["1447327197421560", "The Fetch Market interior before opening"], ["1447327270754886", "Street-level view of the future market entrance"]] },
      { kicker: "Build the relationship", title: "Know the business behind the announcement.", paragraphs: ["Consulting and kitchen visits gave the partnership a closer connection to what Fetch was preparing to offer. The menu, the chef's experience, and the mix of market goods gave the early messaging substance beyond a coming-soon headline.", "An additional announcement pointed readers to The Exponent and Fetch's website for more information. The combination of personal introductions, a recognizable location, and a next place to learn more helped carry the launch story across channels."], images: [["1478031421017804", "Kay and a Fetch Market partner during the consulting and media partnership"], ["1257575986396683", "Fetch Market coming-soon announcement referencing The Exponent"]] },
    ],
  },
  "sisters-smoothies-feature": {
    summary: "A family business introduction and a coordinated set of five signature-drink ads for Sisters Smoothies at Jackson Crossing.",
    heading: "Five sisters. Five drinks. One recognizable campaign.",
    introduction: ["Sisters Smoothies grew from smoothies at school events to a food truck and a place at Jackson Crossing. Whimsy introduced the five young entrepreneurs and their family's role in building the business, then brought the menu into a colorful series of product ads.", "Each signature smoothie carries a sister's name. That gives the campaign a natural connection between the products on offer and the people behind them."],
    hero: ["755016366652650", "Sisters Smoothies business introduction collage"],
    services: ["Business storytelling", "Product advertising", "Campaign design"],
    sections: [
      { kicker: "The business story", title: "Show the journey behind the counter.", paragraphs: ["The introductory feature celebrated the sisters' progression from school events to their own business in the mall. It recognized their parents' support and invited local customers to encourage young entrepreneurs in their community.", "That background gives a product promotion a more personal starting point. Customers can learn who makes the drinks as well as what they can order."], images: [] },
      { kicker: "The signature menu", title: "Make each flavor easy to recognize.", paragraphs: ["The five ads share a layout, logo placement, and order prompt while changing the fruit, color, and drink name. Strawberry pinks, mango yellows, and darker berry tones give the individual recipes their own character.", "The connected format allows each drink to stand alone in a feed while still looking like part of Sisters Smoothies. Seen together, the series presents a range of choices without losing the family identity at the center of the campaign."], images: [["904318161722469", "The Cee Cee smoothie advertisement"], ["904318165055802", "The Livie mango and banana smoothie advertisement"], ["904318168389135", "The Ila smoothie advertisement"], ["904318171722468", "The Cali strawberry and banana smoothie advertisement"], ["904318158389136", "The Sophie strawberry and mango smoothie advertisement"]] },
    ],
  },
  "alpha-koney-story": {
    summary: "Restaurant advertising and a photo story showing Alpha Koney Island's food, hospitality, and space for group gatherings at Jackson Crossing.",
    heading: "A local favorite, with room for your whole group.",
    introduction: ["Whimsy's work with Alpha Koney Island includes media ads and a business feature following a Jackson County Chamber of Commerce networking event. Together, they tell two useful stories: what is on the menu and how the restaurant can welcome a group.", "The feature invited families, organizations, and networking groups to consider the restaurant for a gathering. Real food and event photographs support that invitation with a look at the meal and the setting."],
    hero: ["772622481558705", "Alpha Koney Island restaurant advertisement featuring its food"],
    services: ["Restaurant advertising", "Food photography", "Business features"],
    sections: [
      { kicker: "The food", title: "Give the menu something people can see.", paragraphs: ["The photographs include wraps, salads, shared platters, and dessert from the restaurant's event spread. A mix of close details and serving views shows individual dishes alongside the way a group meal comes together.", "This collection supports the feature's description of Greek food and hospitality without relying on unrelated food photography. It is the restaurant's own table, ready for its guests."], images: [["1285889786898636", "A filled wrap from Alpha Koney Island"], ["1285889820231966", "Salad served at the restaurant gathering"], ["1285889863565295", "A shared platter of wraps"], ["1285889893565292", "Dessert from the event spread"]] },
      { kicker: "The gathering", title: "Show what hosting a group can look like.", paragraphs: ["The Chamber networking event supplied a real example of the space in use. Photographs move from the restaurant entrance to the serving area and the people gathered inside, making the group-dining invitation concrete.", "Pairing the setting with food details gives the feature more range than a menu ad alone. An organization planning its next get-together can picture both the meal and the atmosphere."], images: [["1285889730231975", "Alpha Koney Island entrance at Jackson Crossing"], ["1285889760231972", "Plates and food arranged for the networking event"], ["1285889916898623", "The restaurant's group event setup"], ["1285889956898619", "Guests gathered for the Chamber networking event"], ["1285889990231949", "Networking guests inside Alpha Koney Island"]] },
    ],
  },
  "grazing-thyme-opening": {
    summary: "Grand-opening coverage introducing Grazing Thyme's new Brooklyn space through the ribbon cutting, café details, and market displays.",
    heading: "A new space deserves a proper introduction.",
    introduction: ["Grazing Thyme's grand opening in Brooklyn offered an opportunity to show the business from several angles: the celebration outside, the comfortable seating inside, and the food and goods available to explore.", "Whimsy's opening-day feature congratulated the business and encouraged people to stop in. The photographs make that invitation useful by showing visitors what the new space actually looks like."],
    hero: ["1404297108391236", "The Grazing Thyme grand-opening ribbon cutting in Brooklyn"],
    services: ["Opening-day coverage", "Location photography", "Local business promotion"],
    sections: [
      { kicker: "Inside the café", title: "Show the atmosphere beyond the front door.", paragraphs: ["The seating, flowers, wall details, and café counter communicate the room's character. Wider photographs help people understand the space; closer views show the care put into the decoration and displays.", "Those details give a new visitor a more complete introduction than the ribbon cutting alone. The opening is the occasion, but the room is part of what people can return to enjoy."], images: [["1404297171724563", "Seating and wall decorations inside Grazing Thyme"], ["1404297278391219", "The café counter and product displays"], ["1404297318391215", "Flowers and decorative details in the café"]] },
      { kicker: "Reasons to explore", title: "Let the small details extend the invitation.", paragraphs: ["The market shelves and counter displays add another side to the story. They show that the visit can include browsing as well as a meal, while the seating photographs communicate the relaxed setting.", "The opening-day feature connects the celebration with the everyday experience of visiting. It gives Grazing Thyme a collection of images that introduce both the new location and its welcoming character."], images: [["1404297225057891", "Market shelves inside Grazing Thyme"], ["1404297381724542", "Products displayed along the café counter"], ["1404297425057871", "The decorated seating bench in the new space"]] },
    ],
  },
  "fox-candles-spotlight": {
    summary: "A small-business spotlight introducing Fox Candles' fragrances, product range, and Jackson Crossing location through product photographs and a personal recommendation.",
    heading: "Make a small discovery easier to find.",
    introduction: ["Fox Candles' spotlight introduced a local maker in the halls at Jackson Crossing, near Ulta Beauty and Citi Trends. The feature paired a practical location description with photographs of the candles customers could browse.", "The range extends beyond candles to car scents and other fragrance products. A later post returned to that everyday use, sharing a personal experience with the car scents and inviting readers to visit."],
    hero: ["1337786245042323", "Rows of labeled Fox Candles jars"],
    services: ["Product features", "Local business promotion", "Social content"],
    sections: [
      { kicker: "The product", title: "Give the range room to speak for itself.", paragraphs: ["The product photographs show rows of jars, recognizable labels, and a variety of fragrances. That is useful detail for a business whose appeal depends on choices a photograph cannot fully convey, such as scent.", "The accompanying copy supplies the missing context by describing the fragrance range and inviting customers to explore it in person. The visuals introduce the products; the words give people a reason to visit."], images: [["1337786278375653", "Fox Candles fragrance jars displayed together"]] },
      { kicker: "An everyday connection", title: "Follow the product beyond the shelf.", paragraphs: ["A later photograph showed a Fox Candles car fragrance in use, alongside the business's packaging. The post described trying a new scent after enjoying the previous one, making the recommendation specific and personal.", "Together, the shelf view and in-use photograph tell a fuller small-business story. Customers can see what is available and how a local purchase can become part of an ordinary day."], images: [["1441182931369320", "Fox Candles car fragrance and branded packaging"]] },
    ],
  },
  "serenity-support": {
    title: "Serenity Consulting & Community Support",
    summary: "Consulting, training, and hands-on volunteering with Serenity Sober Living House, connecting business planning with practical support for its community work.",
    heading: "Turn useful conversations into practical next steps.",
    introduction: ["Whimsy's relationship with Serenity Sober Living House began through Jackson County Chamber of Commerce networking. Conversations with Nicole and the team covered fundraising, training, marketing, branding, media, administration, and opportunities in the local community.", "Follow-up consulting and training brought more focus to advertising, local resources, partnerships, and putting ideas into action. The relationship also included volunteering at the house during Community Impact Day."],
    hero: ["1437973818356898", "Kay with the Serenity team after a consulting and training session"],
    services: ["Business consulting", "Training and planning", "Community volunteering"],
    sections: [
      { kicker: "Consulting and strategy", title: "Connect the mission to a plan the team can use.", paragraphs: ["The sessions considered how fundraising, advertising, and community presence support one another. Discussing local resources and possible collaborations helped put those ideas in the context of the organization's day-to-day work.", "The consultation and training gave the team space to discuss those opportunities together. Each topic returned to the same practical question: how to put the ideas into action in a way that supports the organization's work."], images: [["1416300217190925", "Kay and Nicole during an early Serenity consulting visit"], ["1437973855023561", "Serenity Sober Living House during the consulting visit"]] },
      { kicker: "Community Impact Day", title: "Support also means showing up to help.", paragraphs: ["Whimsy joined the Chamber's Community Impact Day at Serenity, with Jim Hartnett from Harvest Solar lending a hand. The work included weeding, planting flowers, edging, building a fire pit, and clearing a patio.", "The photographs document the volunteers and outdoor work around the house. This was a separate, practical contribution alongside the consulting relationship, supporting the people caring for the home and its grounds."], images: [["1407931211361159", "Volunteers together at Serenity on Community Impact Day"], ["1407931354694478", "Volunteers planting and tending the front garden"], ["1407931418027805", "Kay and a fellow volunteer at the project"], ["1407931501361130", "Flowers and fresh mulch in the garden"], ["1407931568027790", "A volunteer clearing the outdoor area"], ["1407931661361114", "The lawn and garden after work at Serenity"]] },
    ],
  },
  "cascades-ribbon-cutting": {
    summary: "A clear opening-day invitation and event photographs welcoming Cascades Humane Society to its additional location at Jackson Crossing.",
    heading: "Welcome a new neighbor. Explain how to take part.",
    introduction: ["Cascades Humane Society's additional Jackson Crossing location opened with a ribbon cutting and community open house. The invitation brought the ceremony, open-house hours, and pet-viewing opportunity together so visitors could plan their stop.", "Whimsy's coverage followed that invitation with photographs of the gathering. The collection shows the nonprofit's new setting, the people who came to celebrate, and the community connections around the opening."],
    hero: ["1426596552827958", "June 3 grand-opening invitation for Cascades Humane Society at Jackson Crossing"],
    services: ["Opening promotion", "Event photography", "Nonprofit visibility"],
    sections: [
      { kicker: "The invitation", title: "Make the day's different opportunities clear.", paragraphs: ["The opening announcement listed a 12:30 PM ribbon cutting with the Jackson County Chamber of Commerce, an open house from 12:30 to 2:30 PM, and adoptions and pet viewing until 6 PM. Visitors could choose the part of the day that worked for them.", "That practical information matters for a nonprofit opening. The celebration introduces the location, while the longer viewing hours give people another way to engage with its work."], images: [["1426887029465577", "Visitors arriving at the Cascades Humane Society mall location"], ["1426887362798877", "Information and displays inside the new location"]] },
      { kicker: "The gathering", title: "Show the welcome the community brought.", paragraphs: ["The event photographs include remarks, conversations, and the group gathered inside the new space. Wide views establish the turnout while closer views record the people involved in the celebration.", "The follow-up post congratulated Cascades Humane Society and recognized the Chamber and Jackson Crossing. The story continues from the invitation into a record of the day, giving the new location another moment of visibility."], images: [["1426887109465569", "Attendees listening during the opening celebration"], ["1426887206132226", "The crowd inside Cascades Humane Society"], ["1426887249465555", "Opening-day conversations in the new space"], ["1426887299465550", "Speakers and guests at the ribbon-cutting gathering"]] },
    ],
  },
  "social-growth": {
    summary: "A documented six-month snapshot of Jackson Crossing's social audience, supported by local business features and a continuing calendar of community stories.",
    heading: "Give people a reason to keep following.",
    introduction: ["Jackson Crossing's social presence brings together stores, food, entertainment, and community activity. Whimsy's archived progress graphic records the page moving from 191 likes and 243 followers to about 1,400 likes and 1,600 followers over six-plus months.", "Those figures describe the page at the time of the archived update. They are a historical audience snapshot, not a claim about today's totals or a measurement of sales."],
    hero: ["797501532404133", "Archived Jackson Crossing audience comparison at the start, three months, and six months"],
    services: ["Social media strategy", "Business advertising", "Community content"],
    sections: [
      { kicker: "The content", title: "A mall has more than one story to tell.", paragraphs: ["Individual business features give people reasons to discover what is in the halls. Alpha Koney Island's food and the Sisters Smoothies family story are examples of Whimsy's local business content, each giving a tenant a distinct voice within the broader Jackson Crossing presence.", "These examples show the range of the relationship. A food advertisement offers a direct reason to visit, while a business introduction builds familiarity with the people behind the counter."], images: [["772622481558705", "Alpha Koney Island advertising from Whimsy's Jackson Crossing work"], ["755016366652650", "Sisters Smoothies business feature from the Jackson Crossing portfolio"]] },
      { kicker: "An ongoing relationship", title: "Keep the page connected to what is happening locally.", paragraphs: ["Later campaigns continued that mix of tenant promotion and community activity. Student artwork, seasonal visits, and nonprofit openings give the mall's communications a calendar beyond individual shopping offers.", "The approach connects useful information with recognizable local places. Someone following for one business can discover an event or community organization on a later visit to the page."], images: [["1088502653304018", "A later Student Art Show campaign at Jackson Crossing"], ["1426596552827958", "A later Cascades Humane Society opening announcement"]] },
    ],
  },
};
