// Measured mobile heading sizes, with room between the text and container edges.
export const mobileHeadingSizes: Record<string, string> = {
  "Alpha Koney|Islands Story": "min(64px, 12.21cqw)",
  "Cascades Humane|Society|Grand Opening": "min(64px, 8.67cqw)",
  "A warm welcome.|A chance for a new beginning.": "min(36px, 5.33cqw)",
  "Promote the grand opening.": "min(32px, 5.79cqw)",
  "Keep the invitation open.": "min(32px, 6.44cqw)",
  "Better lives for animals.|Companionship for people.": "min(36px, 6.07cqw)",
  "Fetch Market|Launch": "min(64px, 12.21cqw)",
  "Finish with something|worth remembering.": "min(36px, 7.32cqw)",
  "A historic spot,|with something new on the way.": "min(32px, 5.2cqw)",
  "Heavenly Bakes & Cakes|Advertising": "min(64px, 6.47cqw)",
  "Put the baker's creativity|on the menu.": "min(36px, 6.4cqw)",
  "Bring a local baker into|the holiday plans.": "min(36px, 6.92cqw)",
  "Give the work behind each|treat a wider audience.": "min(36px, 6.05cqw)",
  "Ingendahl Acres|Branding": "min(64px, 9.9cqw)",
  "A farm identity with character.": "min(36px, 5.25cqw)",
  "Small stickers.|A clear sense of place.": "min(36px, 7.04cqw)",
  "Give a small business|something people can remember.": "min(36px, 5cqw)",
  "A clear path from|curiosity to booking.": "min(36px, 7.86cqw)",
  "Malloween at|Jackson Crossing": "min(64px, 9.09cqw)",
  "Miss Crossroads|& Teen": "min(64px, 9.77cqw)",
  "Put opportunity in the spotlight.": "min(36px, 5.06cqw)",
  "Scholarship, service,|and local representation.": "min(32px, 6.42cqw)",
  "Show what representing|a community can mean.": "min(32px, 6.61cqw)",
  "Make room for the businesses|and causes along the way.": "min(36px, 5.38cqw)",
  "A clearer invitation.|A stronger local connection.": "min(36px, 5.68cqw)",
  "Multiverse|Adventurers Guild": "min(64px, 8.96cqw)",
  "A complete game, with a|place for every player.": "min(36px, 6.48cqw)",
  "A dependable way to speak,|listen, and play.": "min(36px, 5.73cqw)",
  "A character sheet that|does the work with you.": "min(36px, 6.73cqw)",
  "Keep the rulebook connected|as it grows.": "min(36px, 5.46cqw)",
  "Bring the reference and|the tools to the table.": "min(36px, 6.8cqw)",
  "The same game, ready|to take to the table.": "min(36px, 7.1cqw)",
  "Serenity Consulting|& Community Support": "min(64px, 7.5cqw)",
  "Sisters Smoothies|Feature": "min(64px, 8.85cqw)",
  "More control over the sound|coming from a browser.": "min(36px, 6.32cqw)",
  "Jackson County|Student Art Show": "min(64px, 9.15cqw)",
  "Valentine’s at|Jackson Crossing": "min(64px, 9.09cqw)",
  "Show the gift, then explain|where to find it.": "min(36px, 6cqw)",
  "A personal reason to visit.": "min(36px, 6.13cqw)",
  "Welcome Home|Organization": "min(64px, 10.41cqw)",
  "Start with the people|behind the mission.": "min(36px, 7.6cqw)",
  "Make getting involved|feel possible.": "min(36px, 7.39cqw)",
  "Give good work a clearer|way to reach people.": "min(36px, 6.44cqw)",
  "Know when an application|needs attention.": "min(36px, 6.67cqw)",
  "Check several services without|waiting on the slowest one.": "min(36px, 5.68cqw)",
  "Read the whole system,|then focus on a service.": "min(36px, 7.41cqw)",
  "Test changes without duplicating|production incidents.": "min(36px, 5.5cqw)"
};
