export const softwareProjects = [
  {
    slug: "lakeland-website",
    title: "Lakeland Cabaret",
    kind: "Business website",
    summary: "A responsive website bringing entertainment services, pricing, and event inquiries together in one recognizable brand.",
    image: "/work/lakeland%20cabaret/site.png",
    thumbnail: "/work/lakeland%20cabaret/site-wide.png",
    alt: "Lakeland Cabaret website with entertainment services and event photography.",
    intro: "Lakeland Cabaret brings music, fire performance, photography, video, and wedding ceremonies together. We designed and built its public website to give those different services a clear home, with practical pricing information and a direct path to planning an event.",
    sections: [
      { title: "Organize the offering", copy: "Service descriptions, pricing, and inquiry links help visitors understand what is available and how the different options can work together." },
      { title: "Make the brand recognizable", copy: "Deep blue, warm yellow, distinctive typography, and real performance photography carry the business’s personality across the site." },
      { title: "Build for everyday use", copy: "Responsive navigation and layouts adapt to phones and desktops. Accessible markup, optimized images, and page metadata support a maintainable production website." },
    ],
    link: "https://lakelandcabaret.com/",
    linkLabel: "Visit Lakeland Cabaret",
    source: "https://johnbieniek.com/projects/lakeland-cabaret",
  },
  {
    slug: "multiverse-adventurers-guild",
    title: "Multiverse Adventurers Guild",
    kind: "Accessible web application",
    summary: "Game rules, playable character sheets, and accessible controls that bring a tabletop adventure into the browser.",
    image: "/services/multiverse/home-page-desktop.png",
    alt: "Multiverse Adventurers Guild website with guides, rules, and character tools.",
    intro: "A tabletop roleplaying game needs more than a place to read the rules. This application brings the publication and the tools for playing it together, so players can create characters, follow references, and roll dice in one place.",
    sections: [
      { title: "A connected rulebook", copy: "Guides for players and Game Masters organize the game into readable sections. Links connect character choices to the rules that explain them." },
      { title: "Characters ready to play", copy: "An interactive sheet keeps statistics, equipment, notes, and dice rolls together. Browser saves and character-file import and export let players return to their heroes." },
      { title: "More ways to participate", copy: "Responsive layouts support play on phones and larger screens. Typed and spoken commands offer another way to navigate rules and use character tools." },
    ],
    detailImage: "/services/multiverse/playable-sheet.png",
    detailAlt: "Playable Multiverse character sheet with statistics, skills, equipment, and dice controls.",
    detailCaption: "Character creation and play tools share the same application as the rules.",
    link: "https://multiverseadventurersguild.com/",
    linkLabel: "Explore the game",
    source: "https://johnbieniek.com/projects/multiverse-adventurers-guild",
  },
  {
    slug: "sonic-shielding",
    title: "Sonic Shielding",
    kind: "Browser extension",
    summary: "Local audio processing and adjustable controls for a more comfortable listening experience in Chrome and Brave.",
    image: "/work/software/sonic-advertisement.png",
    alt: "Sonic Shielding advertisement promoting more comfortable browser audio, with original and protected waveforms.",
    thumbnail: "/work/software/sonic-advertisement-card.png",
    thumbnailAlt: "Sonic Shielding advertisement: Softer sound. Smarter browsing. Original and protected waveforms illustrate sound reduction.",
    intro: "Sonic Shielding gives listeners control over harsh browser audio. The extension softens sudden peaks and piercing tones while aiming to keep speech and useful sounds recognizable.",
    sections: [
      { title: "Control each tab", copy: "Listeners choose which tabs to protect. Audio controls make it possible to adjust the response to peaks, tones, and alarms." },
      { title: "A personal listening profile", copy: "A saved nine-band profile lets listeners tune frequency reductions. The audio processor responds to the sound rather than lowering everything by the same amount." },
      { title: "Private by design", copy: "Audio processing happens on the listener’s device. The extension does not record or upload audio for remote analysis." },
    ],
    detailImage: "/work/software/sonic-profile.png",
    detailAlt: "Sonic Shielding frequency controls for a saved listening comfort profile.",
    detailCaption: "Adjustable frequency controls put listening preferences in the user’s hands.",
    link: "https://johnbieniek.com/projects/sonic-shielding/home",
    linkLabel: "Explore Sonic Shielding",
    source: "https://johnbieniek.com/projects/sonic-shielding",
  },
  {
    slug: "whimsy-warden",
    title: "Whimsy’s Warden",
    kind: "Monitoring & alerts",
    summary: "A service-health dashboard and email alerts that help us keep watch over Whimsy’s applications.",
    image: "/work/software/warden-dashboard.png",
    alt: "Whimsy’s Warden dashboard showing service availability, response times, and production and beta filters.",
    intro: "Keeping a website useful includes knowing when something needs attention. Whimsy’s Warden monitors application availability and response times, bringing service checks and incident alerts into one operational view.",
    sections: [
      { title: "Check services regularly", copy: "Scheduled checks monitor production applications and stable beta deployments. Concurrent probes and timeouts keep one slow service from holding up the whole check." },
      { title: "See what needs attention", copy: "A responsive dashboard brings together service health, response times, and the latest check. Environment filters help narrow the view." },
      { title: "Make alerts useful", copy: "Email alerts report new outages and slow responses. Stored incident state suppresses repeated notifications while the same problem continues." },
    ],
    link: "https://experiencewhimsy.com/warden/",
    linkLabel: "Open Warden",
    source: "https://johnbieniek.com/projects/whimsy-warden",
  },
];
