export const adCampaignImages = [
  {
    "src": "/services/ad-campaign/sisters-smoothies-cee-cee.jpg",
    "alt": "Sisters Smoothies ad for The Cee Cee, a strawberry, cherry, blueberry, and banana smoothie on a pink background."
  },
  {
    "src": "/services/ad-campaign/sisters-smoothies-livie.jpg",
    "alt": "Sisters Smoothies ad for The Livie, a mango and banana smoothie on a golden background."
  },
  {
    "src": "/services/ad-campaign/sisters-smoothies-cali.jpg",
    "alt": "Sisters Smoothies ad for The Cali, a strawberry and banana smoothie on a dark strawberry background."
  },
  {
    "src": "/services/ad-campaign/sisters-smoothies-sophie.jpg",
    "alt": "Sisters Smoothies ad for The Sophie, a strawberry, mango, and banana smoothie on a pink background."
  }
] as const;

export const services = [
  {"slug":"ad-campaign","name":"AD CAMPAIGN","price":"$300","image":"/services/ad-campaign/sisters-smoothies-livie.jpg","intro":"Four coordinated ads give your business a consistent presence while letting each message do a different job. Using your approved copy, logo, colors, and images, we match your company’s tone, from playful and energetic to polished and professional. Each design makes the offer clear and gives people a specific next step.\n\nFrom grand openings and holiday promotions to community events and sales campaigns, we help the visuals fit the occasion without losing your identity. Your four ads can introduce an offer, highlight a product, share event details, and remind people to act. Our work with Jackson Crossing includes seasonal advertising and community events such as Mall-O-Ween.\n\nOur local work includes campaigns for Jackson Crossing, Five Below, Bath & Body Works, Alpha Koney Island, Buffalo Wild Wings, House of Umami, and many more. We have also created ads for the local radio stations K-105.3 and 106.9 FM. We bring that experience across retail, food, and community promotion to your campaign.","need":["Your campaign goal and intended audience","The offer, event details, and approved copy","Logo, brand colors, and available photos","Where the ads will appear and the required sizes","Your deadline and one person to approve the designs"],"deliverables":["4 custom ad designs","Collaborative campaign planning","Coordinated campaign visuals","Clear calls to action","Ready-to-use digital files","Follow-up email support"],"process":["Confirm the audience, offer, and ad formats","Design four coordinated ads","Review the designs and deliver final files"]},
  { slug: "business-consulting-session", name: "Buisness consulting session", price: "$300", image: "/service%201.jpg", intro: "Most professionals have a deep understanding of their industries' nuances. However, a successful business has to step outside core competencies and deal with finance, marketing, technology, and everything else associated with turning that industrial knowledge into quarterly profits. Whimsy brings practical outside perspective to business decisions, operations, systems, media, and marketing. We help you turn your industry knowledge into a clear plan for growth.\n\nThis focused 90-minute working session is designed to take you from uncertainty to action, whether you are planning a launch, considering a partnership, improving operations, or deciding how to grow. We examine your audience, current efforts, budget, timing, and constraints, then decide what deserves attention first. You leave knowing what to do, what can wait, and why.", need: ["Your main goal, problem, or decision", "A short description of your business and audience", "Relevant numbers, websites, profiles, materials, or past work", "What you have already tried, what happened, and known roadblocks", "Your available budget, timeline, and known constraints", "The people needed to make decisions during the session"], deliverables: ["Preparation and pre-session review", "90-minute working session", "Written Strategy Brief within three business days", "Decision framework and implementation roadmap", "Follow-up email support"], process: ["Clarify your goal and the real problem", "Pressure-test options, opportunities, and risks", "Define owners, priorities, and next steps"] },
  { slug: "brand-advertising-plan", name: "Brand & Advertising Plan", price: "$1,000", image: "/advertising%20plan.png", intro: "Give your company one clear message and a practical plan for sharing it over the next three months. We work with you to understand your audience, review your existing brand, and connect your advertising to a goal that matters to your business.\n\nYour 90-day plan brings together a brand audit, audience profiles, brand and visual style guidance, and a recommended mix of channels. You will know what to say, how your materials should look, where to share them, and when to put each part of the plan to work.\n\nWe also create 12 custom digital ads and plan how to use them across the three months. All 12 ads will run on the Whimsy website during your campaign, and follow-up email support helps you put the plan into practice.", need: ["Your business goals and priority offers for the next three months", "Existing logos, brand files, photos, and marketing materials", "Your website and current social or advertising channels", "What you know about your customers and their questions", "Past campaign, website, or sales results, if available", "Upcoming events, launch dates, and approved offer details", "Your promotion budget and capacity to publish and respond", "One decision-maker for feedback and approvals"], deliverables: ["Brand audit and audience profiles", "Unified company message", "Brand and visual style guide", "Channel guidance and 90-day calendar", "12 custom digital ads", "All 12 ads on the Whimsy website", "Follow-up email support"], process: ["Review your brand, goals, and audience", "Shape the message, style, and 12 ads", "Plan the rollout and Whimsy site placements"] },
  { slug: "website-support", name: "Website Support", price: "$100/hour", image: "/website%20support.jpg", intro: "Keep your website current, fix what is broken, and add the features your business needs. We provide hands-on help with existing websites, from a quick content change to a more involved technical improvement. Bring us a single request or a list of things you have been meaning to tackle. Here are some of the ways we can help:", need: ["Your website address and platform, if known", "A prioritized list of requests and your preferred timing", "Examples of the issue and steps to reproduce it", "Relevant website, hosting, or code access", "Approved text, images, and files for updates", "One contact to review and approve the work"], deliverables: ["Content or design updates", "Technical fixes", "Feature requests", "Accessibility improvements", "Completion notes", "Any language"], process: ["Review the request", "Estimate and prioritize", "Implement, test, and hand off"] },
  {"slug":"website-transfer","name":"Website Transfer","price":"$750","image":"/domain%20change%20image.png","intro":"Have you outgrown Wix or another website builder that makes everyday changes harder than they should be? We move your website to a setup that gives you more control, while keeping the domain your customers already know. Your new setup includes full access to our CMS (content management system), so you can update your website content yourself for free, without needing us. We review every existing page, image, form, and feature so the move preserves the content and functionality your business relies on.\n\nSome platforms need a rebuild rather than a simple file transfer. We plan that work with you, confirm how each feature will carry over, and include agreed updates to existing text and images. You receive access to your content and website accounts, Cloudflare Web Analytics, and follow-up email support. New pages, additional features, and larger redesigns are available as well, just ask!","need":["Your current website address and platform","Access to your website, hosting, and domain account","A list of all pages and important features","Details of forms, bookings, payments, and connected tools","Current business email setup","Original content, images, and downloadable files where available","The content updates you want included","Your goals, preferred launch window, and one person for approvals"],"deliverables":["Domain and DNS configuration","Existing page and functionality migration","Basic website updates","Launch verification","Content management system access","Analytics","Follow-up email support"],"process":["Review every page, feature, and account","Build the replacement and test it with you","Connect your domain, verify, and hand over"]},
  { slug: "single-page-website", name: "Single-Page Website", price: "$750", image: "/services/lakeland%20site.png", intro: "A complete, responsive website brings your business, event, or organization together on one focused page. We build an eye-catching introduction, space to explain your services, and a clear way to contact you, with your photos and message arranged for phones, tablets, and desktops. You get full access to our CMS (content management system), so you can update your website content yourself for free, without needing us.\n\nWe review your content and work with you to shape a design around your goals, ideas, and brand. Your feedback guides the design as we build the finished page. Custom email addresses, analytics, and follow-up email support are included. Need interactive elements, booking tools, or more room to grow? We can discuss those options and scope additional features around your goals.", need: ["Your business goals and intended audience", "What visitors should know or do on the page", "Design ideas, inspiration, or example websites", "Required sections, features, and accessibility needs", "Approved logo, photos, and brand colors", "Core message, service information, and contact details", "Domain details and any existing website", "Your preferred launch date and priorities", "One decision-maker for feedback"], deliverables: ["Request and content review", "Collaborative website design", "One responsive page", "Content management system access", "Custom email addresses", "Analytics", "Follow-up email support"], process: ["Organize the story", "Design and build", "Review, refine, and launch"] },
  { slug: "five-page-website", name: "Five-Page Website", price: "$2,500", image: "/large home page MAG.png", intro: "A complete, responsive website with room for rich content. You get full access to our CMS (content management system), so you can update content across your pages yourself for free, without needing us. We offer the option to add interactive tools that make the site part of the experience. We recommend an eye catching home page, an interactive contact page, and several pages to enumerate your offerings. Five pages is not a hard limit on size and we’re exited to work with you to meet your needs. We do much more than simple webpages. If you need interactive elements or full blown web applications we can integrate that functionality into your new website!", need: ["Brand assets, logos, and photography", "Page goals, content, and feature ideas", "Written copy of desired statements", "Domain access or desired website name", "Availability for a planning meeting", "Timely feedback"], deliverables: ["Request and content review", "Design session", "Five responsive pages", "Content management system access", "Interactive feature planning", "Custom email addresses", "Analytics", "Follow-up email support"], process: ["Plan pages and user journeys", "Design the content and interactions", "Build, test, train, and launch"] },
] as const;

export const caseStudies = [
  { slug:"back-to-school-bash", file:"1478820320938914.jpg", title:"Back to School Bash", client:"Jackson Crossing", category:"Community events", event:"A calm, low-stimulation Back to School Bash", summary:"A welcoming school-year kickoff designed for families who benefit from a quieter environment.", facts:["Free loaded backpacks and hot-meal vouchers while supplies lasted","School photos, business headshots, library-card sign-up, coloring, drinks, and a mascot visit","Attendance grew to more than three times the previous year"], images:["1478820320938914.jpg","797501532404133.jpg"] },
  { slug:"social-growth", file:"797501532404133.jpg", title:"Social Growth Campaign", client:"Jackson Crossing", category:"Advertising", event:"Six months of consistent mall storytelling", summary:"A practical social strategy that made tenants, events, and community value visible week after week.", facts:["The archived campaign reports growth from 191 likes and 243 followers to 1.4K likes and 1.6K followers","Combined promotional graphics, event coverage, and local-business features","Created a repeatable voice for a major regional shopping center"], images:["797501532404133.jpg","760991819388438.jpg"] },
  { slug:"student-art-show", file:"1385435016944112.jpg", title:"Student Art Show", client:"Jackson County Schools", category:"Community events", event:"Jackson County student and teacher appreciation", summary:"An exhibition and appreciation day that put young artists and their schools at the center.", facts:["Work represented more than 25 local schools","Promotion included food trucks, music, and a student/teacher appreciation day","Campaign materials connected school pride with an easy public invitation"], images:["1385435016944112.jpg","837501851737434.jpg"] },
  { slug:"community-connections", file:"1426596552827958.jpg", title:"Community Connections", client:"Jackson Crossing", category:"Media", event:"Ongoing community and tenant storytelling", summary:"A visual content series showing the people, organizations, and moments that make the mall a gathering place.", facts:["On-location content and partner features","A consistent community-first editorial approach","Reusable photography and social creative"], images:["1426596552827958.jpg","1233972312090384.jpg"] },
  { slug:"holiday-in-the-halls", file:"994558686031749.jpg", title:"Holiday in the Halls", client:"Jackson Crossing", category:"Advertising", event:"Jackson Crossing holiday season", summary:"A coordinated holiday campaign spanning social creative, community promotion, and broadcast.", facts:["Whimsy contributed script, directing, and casting for a holiday commercial","The commercial aired across HGTV, USA, Food Network, TBS, Bravo, AMC, TLC, and Freeform","Seasonal work supported a clear, warm local message"], images:["994558686031749.jpg","944490204371931.jpg"] },
  { slug:"jackson-county-fair", file:"894472109373741.jpg", title:"Jackson County Fair", client:"Community campaign", category:"Media", event:"Jackson County Fair promotion", summary:"Bright, timely creative built to make schedules and fair-day invitations easy to notice and share.", facts:["Event-focused social assets","Clear hierarchy for dates and attractions","Flexible campaign creative for repeated promotion"], images:["894472109373741.jpg","894475189373433.jpg"] },
  { slug:"local-business-features", file:"1233972312090384.jpg", title:"Local Business Features", client:"Local organizations", category:"Brand support", event:"Small Business Saturday and tenant spotlights", summary:"A recurring feature series giving local owners a useful, human introduction to new audiences.", facts:["Story-led profiles instead of one-size-fits-all ads","Photography and captions shaped around each business","Cross-promotion through established community channels"], images:["1233972312090384.jpg","1233619748792307.jpg"] },
  { slug:"brand-social", file:"906381761516109.jpg", title:"Brand & Social Campaigns", client:"Local business clients", category:"Websites", event:"Multi-client creative support", summary:"Flexible design and digital support for businesses that need a steady creative partner.", facts:["Campaign concepts, ads, posters, and social graphics","Brand-aware templates for faster publishing","Website and online-presence support when the campaign needs a destination"], images:["906381761516109.jpg","985893490231602.jpg"] },
] as const;
