export const adCampaignImages = [
  {
    "src": "/services/ad-campaign/sisters-smoothies-cee-cee.jpg",
    "alt": "Sisters Smoothies ad for The Cee Cee, a strawberry, cherry, blueberry, and banana smoothie on a pink background."
  },
  {
    "src": "/services/ad-campaign/sisters-smoothies-livie.jpg",
    "alt": "Sisters Smoothies ad for The Livie, a mango and banana smoothie on a golden background."
  },
  {
    "src": "/services/ad-campaign/sisters-smoothies-cali.jpg",
    "alt": "Sisters Smoothies ad for The Cali, a strawberry and banana smoothie on a dark strawberry background."
  },
  {
    "src": "/services/ad-campaign/sisters-smoothies-sophie.jpg",
    "alt": "Sisters Smoothies ad for The Sophie, a strawberry, mango, and banana smoothie on a pink background."
  }
] as const;

export const services = [
  {"slug":"ad-campaign","name":"AD CAMPAIGN","price":"$300","image":"/services/ad-campaign/sisters-smoothies-livie.jpg","intro":"Four coordinated ads give your business a consistent presence while letting each message do a different job. Using your approved copy, logo, colors, and images, we match your company’s tone, from playful and energetic to polished and professional. Each design makes the offer clear and gives people a specific next step.\n\nFrom grand openings and holiday promotions to community events and sales campaigns, we help the visuals fit the occasion without losing your identity. Your four ads can introduce an offer, highlight a product, share event details, and remind people to act. Our work with Jackson Crossing includes seasonal advertising and community events such as Mall-O-Ween.\n\nOur local work includes Jackson Crossing and promotions featuring Bath & Body Works, Alpha Koney Island, Banter by Piercing Pagoda, and Sisters Smoothies. We have also created ads for K-105.3 and 106.9 FM. We bring that experience across retail, food, and community promotion to your campaign.","need":["Your campaign goal and intended audience","The offer, event details, and approved copy","Logo, brand colors, and available photos","Where the ads will appear and the required sizes","Your deadline and one person to approve the designs"],"deliverables":["4 custom ad designs","Coordinated campaign visuals","Clear calls to action","Ready-to-use digital files","Follow-up email support"],"process":["Confirm the audience, offer, and ad formats","Design four coordinated ads","Review the designs and deliver final files"]},
  { slug: "business-consulting-session", name: "Buisness consulting session", price: "$300", image: "/service%201.jpg", intro: "Most professionals have a deep understanding of their industries' nuances. However, a successful business has to step outside core competencies and deal with finance, marketing, technology, and everything else associated with turning that industrial knowledge into quarterly profits. Whimsy brings practical outside perspective to business decisions, operations, systems, media, and marketing. We help you turn your industry knowledge into a clear plan for growth.\n\nThis focused 90-minute working session is designed to take you from uncertainty to action, whether you are planning a launch, considering a partnership, improving operations, or deciding how to grow. We examine your audience, current efforts, budget, timing, and constraints, then decide what deserves attention first. You leave knowing what to do, what can wait, and why.", need: ["Your main goal, problem, or decision", "A short description of your business and audience", "Relevant numbers, websites, profiles, materials, or past work", "What you have already tried, what happened, and known roadblocks", "Your available budget, timeline, and known constraints", "The people needed to make decisions during the session"], deliverables: ["Preparation and pre-session review", "90-minute working session", "Written Strategy Brief within three business days", "Decision framework and implementation roadmap", "Follow-up email support"], process: ["Clarify your goal and the real problem", "Pressure-test options, opportunities, and risks", "Define owners, priorities, and next steps"] },
  { slug: "brand-advertising-plan", name: "Brand & Advertising Plan", price: "$1,000", image: "/advertising%20plan.png", intro: "A clear message and 90-day promotion plan built around your audience, budget, and capacity.", need: ["Existing brand files", "Business and campaign goals", "Past advertising results, if available"], deliverables: ["Brand and message audit", "Audience and channel direction", "90-day advertising plan", "Omnichannel strategy", "Marketing brand style guide", "Follow-up email support"], process: ["Audit what exists", "Shape the message system", "Map campaigns across the right channels"] },
  { slug: "website-support", name: "Website Support", price: "$100/hour", image: "/website%20support.jpg", intro: "Reliable updates and technical help for a site that needs to stay useful, current, and easy to navigate.", need: ["Website and platform details", "Languages used", "Admin access", "Any new media and images", "Prioritized update list"], deliverables: ["Content or design updates", "Technical fixes", "Feature requests", "Accessibility improvements", "Completion notes", "Any language"], process: ["Review the request", "Estimate and prioritize", "Implement, test, and hand off"] },
  { slug: "website-transfer", name: "Website Transfer", price: "$750", image: "/domain%20change%20image.png", intro: "A carefully managed move that protects your visitors, domain, and launch-day confidence.", need: ["Registrar and hosting access", "Current site credentials", "Preferred launch window"], deliverables: ["Domain and DNS configuration", "Redirect and form checks", "Basic website updates", "Launch verification", "Follow-up email support"], process: ["Inventory the current setup", "Prepare the destination", "Move, verify, and monitor"] },
  { slug: "single-page-website", name: "Single-Page Website", price: "$750", image: "/services/lakeland%20site.png", intro: "A complete, responsive website brings your business, event, or organization together on one focused page. We build an eye-catching introduction, space to explain your services, and a clear way to contact you, with your photos and message arranged for phones, tablets, and desktops.\n\nWe review your content, offer three custom design choices, and build the finished page around your selected direction. Custom email addresses and follow-up email support are included. Need interactive elements, booking tools, or more room to grow? We can discuss those options and scope additional features around your goals.", need: ["Your business goals and intended audience", "What visitors should know or do on the page", "Design ideas, inspiration, or example websites", "Required sections, features, and accessibility needs", "Approved logo, photos, and brand colors", "Core message, service information, and contact details", "Domain details and any existing website", "Your preferred launch date and priorities", "One decision-maker for feedback"], deliverables: ["Request and content review", "Three custom design choices", "One responsive page", "Custom email addresses", "Follow-up email support"], process: ["Organize the story", "Design and build", "Review, refine, and launch"] },
  { slug: "five-page-website", name: "Five-Page Website", price: "$2,500", image: "/large home page MAG.png", intro: "A complete, responsive website with room for rich content. We offer the option to add interactive tools that make the site part of the experience. We recommend an eye catching home page, an interactive contact page, and several pages to enumerate your offerings. Five pages is not a hard limit on size and we’re exited to work with you to meet your needs. We do much more than simple webpages. If you need interactive elements or full blown web applications we can integrate that functionality into your new website!", need: ["Brand assets, logos, and photography", "Page goals, content, and feature ideas", "Written copy of desired statements", "Domain access or desired website name", "Availability for a planning meeting", "Timely feedback"], deliverables: ["Request and content review", "Design session", "Five responsive pages", "Interactive feature planning", "Custom email addresses", "Analytics", "Follow-up email support"], process: ["Plan pages and user journeys", "Design the content and interactions", "Build, test, train, and launch"] },
] as const;

export const caseStudies = [
  { slug:"back-to-school-bash", file:"1478820320938914.jpg", title:"Back to School Bash", client:"Jackson Crossing", category:"Community events", event:"A calm, low-stimulation Back to School Bash", summary:"A welcoming school-year kickoff designed for families who benefit from a quieter environment.", facts:["Free loaded backpacks and hot-meal vouchers while supplies lasted","School photos, business headshots, library-card sign-up, coloring, drinks, and a mascot visit","Attendance grew to more than three times the previous year"], images:["1478820320938914.jpg","797501532404133.jpg"] },
  { slug:"social-growth", file:"797501532404133.jpg", title:"Social Growth Campaign", client:"Jackson Crossing", category:"Advertising", event:"Six months of consistent mall storytelling", summary:"A practical social strategy that made tenants, events, and community value visible week after week.", facts:["The archived campaign reports growth from 191 likes and 243 followers to 1.4K likes and 1.6K followers","Combined promotional graphics, event coverage, and local-business features","Created a repeatable voice for a major regional shopping center"], images:["797501532404133.jpg","760991819388438.jpg"] },
  { slug:"student-art-show", file:"1385435016944112.jpg", title:"Student Art Show", client:"Jackson County Schools", category:"Community events", event:"Jackson County student and teacher appreciation", summary:"An exhibition and appreciation day that put young artists and their schools at the center.", facts:["Work represented more than 25 local schools","Promotion included food trucks, music, and a student/teacher appreciation day","Campaign materials connected school pride with an easy public invitation"], images:["1385435016944112.jpg","837501851737434.jpg"] },
  { slug:"community-connections", file:"1426596552827958.jpg", title:"Community Connections", client:"Jackson Crossing", category:"Media", event:"Ongoing community and tenant storytelling", summary:"A visual content series showing the people, organizations, and moments that make the mall a gathering place.", facts:["On-location content and partner features","A consistent community-first editorial approach","Reusable photography and social creative"], images:["1426596552827958.jpg","1233972312090384.jpg"] },
  { slug:"holiday-in-the-halls", file:"994558686031749.jpg", title:"Holiday in the Halls", client:"Jackson Crossing", category:"Advertising", event:"Jackson Crossing holiday season", summary:"A coordinated holiday campaign spanning social creative, community promotion, and broadcast.", facts:["Whimsy contributed script, directing, and casting for a holiday commercial","The commercial aired across HGTV, USA, Food Network, TBS, Bravo, AMC, TLC, and Freeform","Seasonal work supported a clear, warm local message"], images:["994558686031749.jpg","944490204371931.jpg"] },
  { slug:"jackson-county-fair", file:"894472109373741.jpg", title:"Jackson County Fair", client:"Community campaign", category:"Media", event:"Jackson County Fair promotion", summary:"Bright, timely creative built to make schedules and fair-day invitations easy to notice and share.", facts:["Event-focused social assets","Clear hierarchy for dates and attractions","Flexible campaign creative for repeated promotion"], images:["894472109373741.jpg","894475189373433.jpg"] },
  { slug:"local-business-features", file:"1233972312090384.jpg", title:"Local Business Features", client:"Local organizations", category:"Brand support", event:"Small Business Saturday and tenant spotlights", summary:"A recurring feature series giving local owners a useful, human introduction to new audiences.", facts:["Story-led profiles instead of one-size-fits-all ads","Photography and captions shaped around each business","Cross-promotion through established community channels"], images:["1233972312090384.jpg","1233619748792307.jpg"] },
  { slug:"brand-social", file:"906381761516109.jpg", title:"Brand & Social Campaigns", client:"Local business clients", category:"Websites", event:"Multi-client creative support", summary:"Flexible design and digital support for businesses that need a steady creative partner.", facts:["Campaign concepts, ads, posters, and social graphics","Brand-aware templates for faster publishing","Website and online-presence support when the campaign needs a destination"], images:["906381761516109.jpg","985893490231602.jpg"] },
] as const;
