export const services = [
  { slug: "strategy-session", name: "Strategy Session", price: "$300", image: "/service%201.jpg", intro: "A focused 90-minute working session that turns a crowded idea list into a practical next move.", need: ["Your main goal", "The audience you need to reach", "Current materials, links, and constraints"], deliverables: ["90-minute working session", "Written priorities and next steps", "Recommended tools and timing", "Follow-up email support"], process: ["Listen to the full picture", "Identify the highest-value opportunity", "Build a realistic action plan"] },
  { slug: "brand-advertising-plan", name: "Brand & Advertising Plan", price: "$1,000", image: "/work/906381761516109.jpg", intro: "A clear message and 90-day promotion plan built around your audience, budget, and capacity.", need: ["Existing brand files", "Business and campaign goals", "Past advertising results, if available"], deliverables: ["Brand and message audit", "Audience and channel direction", "90-day advertising plan", "Omnichannel strategy", "Marketing brand style guide", "Follow-up email support"], process: ["Audit what exists", "Shape the message system", "Map campaigns across the right channels"] },
  { slug: "business-consulting", name: "Business Consulting Session", price: "$300", image: "/buisness%20consult.jpg", intro: "Practical outside perspective for an operational question, launch, partnership, or growth decision.", need: ["The decision in front of you", "Relevant numbers and context", "Known roadblocks"], deliverables: ["90-minute operational session", "Decision framework", "Opportunity and risk assessment", "Implementation roadmap", "Concise action summary", "Follow-up email support"], process: ["Clarify the real problem", "Pressure-test the options", "Define owners and next steps"] },
  { slug: "website-support", name: "Website Support", price: "$100/hour", image: "/website%20support.jpg", intro: "Reliable updates and technical help for a site that needs to stay useful, current, and easy to navigate.", need: ["Website and platform details", "Languages used", "Admin access", "Any new media and images", "Prioritized update list"], deliverables: ["Content or design updates", "Technical fixes", "Feature requests", "Accessibility improvements", "Completion notes", "Any language"], process: ["Review the request", "Estimate and prioritize", "Implement, test, and hand off"] },
  { slug: "website-transfer", name: "Domain Change & Website Transfer", price: "$750", image: "/work/957428976411387.jpg", intro: "A carefully managed move that protects your visitors, domain, and launch-day confidence.", need: ["Registrar and hosting access", "Current site credentials", "Preferred launch window"], deliverables: ["Domain and DNS configuration", "Redirect and form checks", "Basic website updates", "Launch verification", "Follow-up email support"], process: ["Inventory the current setup", "Prepare the destination", "Move, verify, and monitor"] },
  { slug: "single-page-website", name: "Single-Page Website", price: "$750", image: "/services/lakeland%20site.png", intro: "A concise, responsive home on the web for a focused offer, event, or growing local organization.", need: ["Approved logo and photos", "Core message and contact details", "One decision-maker for feedback"], deliverables: ["Request and content review", "Three custom design choices", "One responsive page", "Custom email addresses", "Follow-up email support"], process: ["Organize the story", "Design and build", "Review, refine, and launch"] },
  { slug: "five-page-website", name: "Five-Page Website", price: "$2,500", image: "/services/multiverse/home-page-desktop.png", intro: "A complete, responsive website with room for rich content—and the option to add interactive tools that make the site part of the experience.", need: ["Brand assets and photography", "Page goals, content, and feature ideas", "Domain access and timely feedback"], deliverables: ["Request and content review", "Design session", "Five responsive pages", "Interactive feature planning", "Custom email addresses", "Analytics", "Follow-up email support"], process: ["Plan pages and user journeys", "Design the content and interactions", "Build, test, train, and launch"] },
] as const;

export const caseStudies = [
  { slug:"back-to-school-bash", file:"1478820320938914.jpg", title:"Back to School Bash", client:"Jackson Crossing", category:"Community events", event:"A calm, low-stimulation Back to School Bash", summary:"A welcoming school-year kickoff designed for families who benefit from a quieter environment.", facts:["Free loaded backpacks and hot-meal vouchers while supplies lasted","School photos, business headshots, library-card sign-up, coloring, drinks, and a mascot visit","Attendance grew to more than three times the previous year"], images:["1478820320938914.jpg","797501532404133.jpg"] },
  { slug:"social-growth", file:"797501532404133.jpg", title:"Social Growth Campaign", client:"Jackson Crossing", category:"Advertising", event:"Six months of consistent mall storytelling", summary:"A practical social strategy that made tenants, events, and community value visible week after week.", facts:["The archived campaign reports growth from 191 likes and 243 followers to 1.4K likes and 1.6K followers","Combined promotional graphics, event coverage, and local-business features","Created a repeatable voice for a major regional shopping center"], images:["797501532404133.jpg","760991819388438.jpg"] },
  { slug:"student-art-show", file:"1385435016944112.jpg", title:"Student Art Show", client:"Jackson County Schools", category:"Community events", event:"Jackson County student and teacher appreciation", summary:"An exhibition and appreciation day that put young artists and their schools at the center.", facts:["Work represented more than 25 local schools","Promotion included food trucks, music, and a student/teacher appreciation day","Campaign materials connected school pride with an easy public invitation"], images:["1385435016944112.jpg","837501851737434.jpg"] },
  { slug:"community-connections", file:"1426596552827958.jpg", title:"Community Connections", client:"Jackson Crossing", category:"Media", event:"Ongoing community and tenant storytelling", summary:"A visual content series showing the people, organizations, and moments that make the mall a gathering place.", facts:["On-location content and partner features","A consistent community-first editorial approach","Reusable photography and social creative"], images:["1426596552827958.jpg","1233972312090384.jpg"] },
  { slug:"holiday-in-the-halls", file:"994558686031749.jpg", title:"Holiday in the Halls", client:"Jackson Crossing", category:"Advertising", event:"Jackson Crossing holiday season", summary:"A coordinated holiday campaign spanning social creative, community promotion, and broadcast.", facts:["Whimsy contributed script, directing, and casting for a holiday commercial","The commercial aired across HGTV, USA, Food Network, TBS, Bravo, AMC, TLC, and Freeform","Seasonal work supported a clear, warm local message"], images:["994558686031749.jpg","944490204371931.jpg"] },
  { slug:"jackson-county-fair", file:"894472109373741.jpg", title:"Jackson County Fair", client:"Community campaign", category:"Media", event:"Jackson County Fair promotion", summary:"Bright, timely creative built to make schedules and fair-day invitations easy to notice and share.", facts:["Event-focused social assets","Clear hierarchy for dates and attractions","Flexible campaign creative for repeated promotion"], images:["894472109373741.jpg","894475189373433.jpg"] },
  { slug:"local-business-features", file:"1233972312090384.jpg", title:"Local Business Features", client:"Local organizations", category:"Brand support", event:"Small Business Saturday and tenant spotlights", summary:"A recurring feature series giving local owners a useful, human introduction to new audiences.", facts:["Story-led profiles instead of one-size-fits-all ads","Photography and captions shaped around each business","Cross-promotion through established community channels"], images:["1233972312090384.jpg","1233619748792307.jpg"] },
  { slug:"brand-social", file:"906381761516109.jpg", title:"Brand & Social Campaigns", client:"Local business clients", category:"Websites", event:"Multi-client creative support", summary:"Flexible design and digital support for businesses that need a steady creative partner.", facts:["Campaign concepts, ads, posters, and social graphics","Brand-aware templates for faster publishing","Website and online-presence support when the campaign needs a destination"], images:["906381761516109.jpg","985893490231602.jpg"] },
] as const;
