import Image from "next/image";
import { getImageAlt } from "./image-alt";
import Link from "next/link";
import { ArrowRightLeft, CalendarDays, ClipboardList, Crown, Images, Megaphone, Monitor, Palette, PawPrint, Wrench } from "lucide-react";
import squareCollage from "../../collage/square collage.png";
import squareCollageMobile from "../../collage/square collage mobile.png";
import { Partners } from "./site-chrome";
import { LatestNews } from "./latest-news";
import { CreatorCredit } from "./creator-credit";
const highlights = [
  { image: "/work/miss-crossroads/community-carousel.jpg", title: "Miss Crossroads & Teen", copy: "Recruitment ads and community photography sharing the opportunities behind the crown.", slug: "miss-crossroads", Icon: Crown },
  { image: "/work/1385435016944112.jpg", title: "Student Art Show", copy: "A countywide celebration of student creativity from more than 25 local schools.", slug: "student-art-show", Icon: Palette },
  { image: "/work/archive/cascades-kitten-hero.jpg", title: "Cascades Humane Society", copy: "Advertising, promotion, and photography celebrating a new community location.", slug: "cascades-ribbon-cutting", Icon: PawPrint },
  { image: "/work/lakeland%20cabaret/site.png", title: "Lakeland Cabaret", copy: "A new brand and website for memorable performances.", slug: "lakeland-cabaret", Icon: Monitor },
];
const pathways=[{title:"Create",copy:"Content and design that tell your story.",Icon:Images},{title:"Plan",copy:"Clarify goals and build a practical strategy.",Icon:ClipboardList},{title:"Promote",copy:"Campaigns that reach the right audience.",Icon:Megaphone},{title:"Maintain",copy:"Reliable support that keeps your website current.",Icon:Wrench},{title:"Transfer",copy:"Move your domain and website with confidence.",Icon:ArrowRightLeft},{title:"Build online",copy:"Websites, applications, and updates that work.",Icon:Monitor}];
export default function Home(){return <main className="home-page"><section className="home-hero shell"><div className="home-copy"><Image className="home-logo" src="/logo%20tight.png" alt="Whimsy Consulting, Media, Marketing" width={4744} height={2198} priority/><span className="home-logo-dots" aria-hidden="true"/><h1 className="home-tagline">Local knowledge. Creative media. Practical growth.</h1><p>Whimsy helps local businesses and organizations strengthen their brand, promote events, improve their online presence, and make practical decisions about growth. We combine consulting, media, marketing, and website development with firsthand knowledge of the Jackson-area community.</p><div className="actions"><Link className="button" href="/about"><span aria-hidden="true">✦</span><span>About us</span></Link><Link className="button outline" href="/contact"><CalendarDays aria-hidden="true"/><span>Book a consultation</span></Link></div></div><Image className="home-square-collage home-square-collage-desktop" src={squareCollage} alt="Whimsy work collage featuring a ribbon cutting, backpack giveaway, smoothie advertisement, Halloween portraits, fair and concert posters, and local food promotions." sizes="58vw"/><Image className="home-square-collage home-square-collage-mobile" src={squareCollageMobile} alt="Whimsy work collage featuring a ribbon cutting, backpack giveaway, smoothie advertisement, Halloween portraits, fair and concert posters, and local food promotions." sizes="calc(100vw - 56px)"/></section><LatestNews/><section className="campaigns shell"><p className="kicker campaigns-title">Featured Campaigns</p><div className="highlight-grid">{highlights.map(({image,title,copy,slug,Icon})=><Link href={`/work/${slug}`} className="highlight" key={title}><div><Image className={slug==="lakeland-cabaret"?"lakeland-feature-image":undefined} src={image} alt={getImageAlt(image)} fill sizes="25vw"/></div><article><span className="highlight-icon" aria-hidden="true"><Icon/></span><h2>{title}</h2><p>{copy}</p><b>→</b></article></Link>)}</div></section><Partners/><section className="home-bottom shell"><div><p className="kicker pathways-title">Our service pathways</p><div className="pathways">{pathways.map(({Icon,title,copy})=><article key={title}><span className="pathway-icon" aria-hidden="true"><Icon/></span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section><CreatorCredit /></main>}
