"use client";
import Image from "next/image";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useRef, useState } from "react";
import { appVersion } from "./generated-version";

const links = [["/", "Home"], ["/services", "Services & Pricing"], ["/contact", "Contact"]];

export function SiteHeader(){const path=usePathname();return <header className={`site-header shell${path==="/"?" home-header":""}`}><Link href="/" className="nav-logo"><Image src="/logo%20tight.png" alt="Whimsy home" width={4744} height={2198} priority/></Link><nav aria-label="Main navigation">{links.map(([href,label])=><Link key={href} href={href} className={path===href?"active":""}>{label}</Link>)}</nav></header>}

export function SiteFooter(){const [pressed,setPressed]=useState(false);const timer=useRef<ReturnType<typeof setTimeout>|null>(null);const startPress=()=>{timer.current=setTimeout(()=>setPressed(true),550)};const endPress=()=>{if(timer.current)clearTimeout(timer.current);timer.current=null};return <footer><div className="shell"><p>Whimsy · Jackson, Michigan</p><p className={`footer-version${pressed?" pressed":""}`} tabIndex={0} onPointerDown={startPress} onPointerUp={endPress} onPointerCancel={endPress} onPointerLeave={endPress} onClick={()=>pressed&&setPressed(false)}>Consulting · Media · Marketing <small aria-label={`Version ${appVersion}`}>v{appVersion}</small></p></div></footer>}

export function Partners(){return <section className="partners shell" aria-labelledby="partners-title"><h2 id="partners-title">Featured<br/>partners</h2><a className="partner jackson-mark" href="https://shopjacksoncrossing.com/" target="_blank" rel="noopener noreferrer" aria-label="Visit the Jackson Crossing website (opens in a new tab)"><Image className="jackson-crossing-logo" src="/jackson-crossing-logo.png" alt="Jackson Crossing" width={1750} height={899} sizes="(max-width: 700px) 80vw, 24vw"/></a><a className="partner partner-image fetch-partner" href="https://101monroe.com/#commercial" target="_blank" rel="noopener noreferrer" aria-label="Visit the Fetch Market and Deli website (opens in a new tab)"><Image className="fetch-logo" src="/fetch%20logo.jpg" alt="Fetch Market and Deli" width={541} height={540} sizes="(max-width: 700px) 100vw, 24vw"/></a><a className="partner serenity-mark" href="https://www.linkedin.com/company/serenity-sober-living-house/" target="_blank" rel="noopener noreferrer" aria-label="Visit Serenity Sober Living House online (opens in a new tab)"><strong>Serenity</strong><span>SOBER LIVING HOUSE</span><small>“NOT PERFECT, SOBER &amp; FREE”</small></a><a className="partner partner-image lakeland-partner" href="https://lakelandcabaret.com/" target="_blank" rel="noopener noreferrer" aria-label="Visit the Lakeland Cabaret website (opens in a new tab)"><Image className="lakeland-logo" src="/lakeland-cabaret-logo.png" alt="Lakeland Cabaret" width={1900} height={1847} sizes="(max-width: 700px) 110px, 24vw"/></a></section>}

export function AdCollage({className=""}:{className?:string}){const ads=["1478820320938914.jpg","797501532404133.jpg","1385435016944112.jpg","994558686031749.jpg","894472109373741.jpg","1233972312090384.jpg"];return <div className={`ad-collage ${className}`.trim()} aria-label="Selected Whimsy advertising work"><span className="ad-shape ad-shape-solid-one" aria-hidden="true"/><span className="ad-shape ad-shape-solid-two" aria-hidden="true"/><span className="ad-shape ad-shape-frame-one" aria-hidden="true"/><span className="ad-shape ad-shape-frame-two" aria-hidden="true"/>{ads.map((file,index)=><figure key={file} className={`ad-tile ad-tile-${index+1}`}><Image src={`/work/${file}`} alt="" fill sizes="(max-width:700px) 45vw, 22vw"/></figure>)}</div>}

export function Collage({images,labels=[],className=""}:{images:string[];labels?:string[];className?:string}){return <div className={`collage ${className}`.trim()} aria-label="Whimsy community work collage">{images.map((src,index)=><figure key={src} className={`bubble bubble-${index+1}`}><Image src={src} alt="" fill sizes="(max-width: 700px) 45vw, 24vw"/>{labels[index]&&<figcaption>{labels[index]}</figcaption>}</figure>)}</div>}
