export const trainingEditorial = {
  "facebook-meta-basics-training": {
    platform: "Facebook & Meta",
    lead: "Make your next post the start of a better routine.",
    hero: "/services/training/facebook-hero.webp",
    heroAlt: "Facebook icon surrounded by a social post, calendar, and message illustrations.",
    introduction: "Your Facebook page should help people understand your business and know what to do next. We work through your own page, content, and questions together, so every new skill has an immediate use.",
    promise: "An organized page. A finished post. A way forward.",
    overviewTitle: "Turn a page you have into a presence you can manage.",
    overview: [
      "Knowing where to click is only part of the job. A useful business page also needs clear information, recognizable images, and posts that give customers a reason to pay attention. We connect those pieces using your business as the working example.",
      "We start with what customers see, then move behind the scenes into the tools you’ll use to plan, publish, and respond. You practice as we go, with time to ask questions and repeat the steps that feel unfamiliar.",
    ],
    steps: [
      { title: "Get the page in order", copy: "Review your information, images, and settings through the eyes of a potential customer." },
      { title: "Build a useful posting routine", copy: "Find your way around Meta’s tools, plan what to share, and practice managing conversations." },
      { title: "Create your next post", copy: "Bring your message and visuals together in a finished post, ready for you to publish." },
    ],
    preparation: ["Access to your Facebook Business Page and the account that manages it", "A laptop and your usual sign-in and verification method", "Your logo, business photos, and current contact details", "One offer, event, product, or story you would like to promote", "Instagram account access if you want to review the connection"],
    preparationNote: "Already have a page but feel stuck? Bring it as it is. We’ll start with your current setup and the tasks you want to handle more confidently.",
    skills: [
      { title: "Help customers find the essentials", copy: "Check how your page introduces the business. Work through the profile and cover images, About section, contact information, and settings so the basics tell a consistent story.", tags: ["Page information", "Brand consistency", "Customer experience"] },
      { title: "Plan content with a purpose", copy: "Choose a useful subject, write a clear opening, and give readers a next step. Build ideas around what your business already does: products, events, customer questions, and work behind the scenes.", tags: ["Post ideas", "Captions", "Calls to action"] },
      { title: "Find your everyday tools", copy: "Practice creating posts, scheduling content, exploring Stories, and finding messages and comments. Review the Facebook and Instagram connection where it fits your accounts.", tags: ["Meta Business Suite", "Scheduling", "Messages & comments"] },
    ],
    projectTitle: "One real post. Your business. Your voice.",
    projectCopy: "Choose something you actually want to share. We’ll combine your images and message, refine the wording, and check the details together. You finish with a branded post and an understanding of how to create the next one yourself.",
    projectChecks: ["A clear message for your audience", "A photo or graphic that fits your brand", "Accurate details and a useful next step", "A finished post ready to publish"],
    projectImage: "/services/ad-campaign/sisters-smoothies-livie.jpg",
    projectAlt: "Whimsy’s Sisters Smoothies promotional design featuring a colorful drink.",
    projectCaption: "From Whimsy’s campaign work: a focused product promotion for Sisters Smoothies. Your session uses your own business and content.",
    faqs: [
      { question: "Is this a beginner session?", answer: "Yes. We work through the basics at a pace that lets you practice. If you already post occasionally, we can focus on the setup and tools you have been avoiding or want to understand better." },
      { question: "Will we publish during the session?", answer: "We’ll create a finished post together. You decide when to publish it; the goal is to leave you with something ready to use and the confidence to repeat the process." },
      { question: "Does this include running paid ads?", answer: "This session focuses on managing your page and creating content. If you also want a paid advertising campaign, we can discuss the creative, setup, and advertising budget separately." },
      { question: "What if I cannot access my page?", answer: "Let us know before booking so we can discuss the access issue. Working in your own page requires the appropriate account access; account recovery may need to be resolved before the training." },
    ],
  },
  "canva-basics-training": {
    platform: "Canva",
    lead: "Good ideas deserve graphics you’re proud to share.",
    hero: "/services/training/canva-hero.webp",
    heroAlt: "Canva wordmark with layered design boards, color swatches, and typography tools.",
    introduction: "Stop starting from a blank page every time you need a graphic. We’ll organize your brand, work through Canva’s everyday tools, and build a real advertisement together—with you learning the decisions behind the design.",
    promise: "Your brand, organized. Your first ad, finished.",
    overviewTitle: "Make your next design feel like your business.",
    overview: [
      "A template is a starting point. Choosing the right photograph, giving the headline room, and knowing what to leave out are what make the design work for your business. We practice those choices using your own materials.",
      "Together, we bring your logos, photos, colors, and existing graphics into a more useful setup. Then we turn an actual message into an advertisement, building a workflow you can return to for your next promotion.",
      "We highly recommend that you have a Canva Pro subscription for this training, as it will allow you to make the most of our time together.",
    ],
    steps: [
      { title: "Gather your brand", copy: "Find and organize the logos, photographs, and visual details you want to use consistently." },
      { title: "Learn by making", copy: "Explore templates, text, elements, and image tools while shaping a real design." },
      { title: "Finish and use your ad", copy: "Review the layout, check the message, and learn how to save and export the finished piece." },
    ],
    preparation: ["Access to your Canva account and a laptop", "Your logos, business photographs, and any existing graphics", "Brand colors and fonts, if you have them", "The offer, event, or message you want your advertisement to communicate", "An idea of where the design will be used, such as Facebook or a printed flyer"],
    preparationNote: "You do not need a polished brand guide or design experience. Bring what you have, including examples you like and designs you have struggled with.",
    skills: [
      { title: "Build from your own brand", copy: "Gather your logos and photographs, identify the colors and type you use, and organize those assets so your next project is easier to start.", tags: ["Logos & photos", "Colors & type", "Asset organization"] },
      { title: "Make a template your own", copy: "Choose a layout that suits the message, replace generic content, and work with text and elements. Practice spacing, alignment, and visual hierarchy so the most important details stand out.", tags: ["Templates", "Text & elements", "Layout & hierarchy"] },
      { title: "Polish the details", copy: "Work with cropping, image editing, and design adjustments. Explore Background Remover where available, then check legibility and learn how to export for the place your ad will appear.", tags: ["Image editing", "Design adjustments", "Exporting"] },
    ],
    projectTitle: "Leave with an ad. Know how you made it.",
    projectCopy: "Bring a product, event, or offer you want people to notice. We’ll build the advertisement together, working through the headline, image, brand details, and call to action. You keep the design in your account so you can return to it and make future updates.",
    projectChecks: ["Your logo, colors, and imagery", "A headline with a clear visual hierarchy", "The details customers need to act", "A finished advertisement ready to use"],
    projectImage: "/work/valentines/bakes-and-cakes-valentines.webp",
    projectAlt: "Whimsy’s pink Valentine’s sweets advertisement for Heavenly Bakes & Cakes.",
    projectCaption: "From Whimsy’s design work: a seasonal offer for Heavenly Bakes & Cakes. Your session builds an advertisement for your business.",
    faqs: [
      { question: "Do I need design experience?", answer: "No. We start with navigation and the tools you need, then explain the design choices as we make them. The session is built around practice with your own business materials." },
      { question: "Do I need Canva Pro?", answer: "We can work with the account you already have and discuss which features are available to you. Some tools and assets have plan or usage limits, so we’ll use suitable alternatives where needed. A Canva subscription is separate from training." },
      { question: "What kind of advertisement will we make?", answer: "Bring a specific offer, event, product, or service to promote. We’ll agree on one finished design and its intended use, such as a social graphic or a flyer, so the session has a clear outcome." },
      { question: "Can I keep editing the design afterward?", answer: "Yes. We work in your Canva account so you can revisit the design, change details, and use what you learned for your next piece of marketing." },
    ],
  },
};
