import { mkdirSync, readFileSync, writeFileSync } from "node:fs";

const packageJson = JSON.parse(readFileSync(new URL("../package.json", import.meta.url), "utf8"));
const version = packageJson.version;
const output = new URL("../src/app/generated-version.ts", import.meta.url);

mkdirSync(new URL("../src/app/", import.meta.url), { recursive: true });
writeFileSync(output, `// Generated by scripts/generate-version.mjs\nexport const appVersion = "${version}";\n`);
console.log(`Generated app version ${version}`);
